### ISSUE TITLE
Possible leading tokens is missing

### ISSUE THREAD

**Issue by MrMuMu** [b3b00/csly#100]
Hello again,

I have not been able identify the last problem we had talked about possible leading tokens.

I did just a little bit debugging, here what I gathered from that:

this is a valid XPath expression (tested) `-----(2+1)`

when I try to parse, it comes with no problem up to the token `2`.
After that it prompts an error that it has no possible leading tokens as `INTEGER`.

some of the rules

    // root
    [Production("XPath: Expr")]
    public string XPath(string expr)

    // Expr
    [Production("Expr: ExprSingle")]
    public string Expr(string exprSingle)

    // other rules that lead to ArrowExpr
    [Production("ArrowExpr: UnaryExpr")]
    public string ArrowExpr(string unaryExpr)

    [Production("UnaryExpr: MinusOrPlusExpr* ValueExpr")]
    public string UnaryExpr(List<string> uMinusPlus, string valueExpr)

    [Production("ValueExpr: SimpleMapExpr")]
    public string ValueExpr(string simpleMapExpr)

    it continues...

So I decided to connect `ArrowExpr` to `ValueExpr`, so my language will not support unary expressions.
I was able to parse `1-2-(3+4)` without problem.

Then I add `UnaryExpr` again and tried to parse `1-2-(3+4)`, an error occurred. I did another debug session, the error is the same.

Then I tried `1-2-3+4` the error is the same.

Then I tried `1` the error is the same.

Then I connected `ArrowExpr` to `ValueExpr`, every expression that I tried before worked without problem.

So, I again did I debug on working version, and saw that `PossibleLeadingTokens` had `INTEGER`

My guess is that when I use `UnaryExpr`, since there is a `MinusOrPlusExpr`, token types that lead to `ValueExpr` does not taken in to account, however, since `MinusOrPlusExpr` can occur 0 times, token types that lead to `ValueExpr` should be taken into account.

**Comment by b3b00** [comment]
hello,
I am a bit confused with your problem. I checked your netschematron repo quickly and it seems to work without any parse error.
Would you mind provide minimal reproduction case : 

- lexer
- grammar
- source to parse and expected result

**Comment by MrMuMu** [comment]
repo is not up to date right now, i will post here when it is ready

**Comment by b3b00** [comment]
I 've just push a fix on branch [bugfix/#100](https://github.com/b3b00/csly/tree/bugfix/%23100).
I 've also made a PR to your repo to solve a small bug.

Could you checkout my repo on branch bugfix/#100 and test to see if fix is ok for you ?
i am merging on main dev branch nevertheless


Thanks for your help.

Olivier

**Comment by b3b00** [comment]
.

**Comment by MrMuMu** [comment]
It seems to be working thank you very much. I'm curious tho, what was the problem can you tell me in a short way?
