### ISSUE TITLE
ValueOption warnings

### ISSUE THREAD

**Issue by MrMuMu** [b3b00/csly#104]
Hello again,

I'm getting following warnings from `BuildResult` it seems related to `ValueOption`:

    "non terminal [GROUP-COMPARATOR-StringConcatExpr] is never used."
    "non terminal [GROUP-TO[d]-AdditiveExpr] is never used."
    "non terminal [GROUP-Argument-ExtraArgumentList] is never used."

Also,

I have the following rule:

    [Production("RangeExpr: AdditiveExpr (TO [d] AdditiveExpr)?")]
    public object RangeExpr(object additiveExpr, ValueOption<Group<XPathToken, object>> optionalGroup)

When I delete the optional group clause it works without problem, but when I add the rule, the program gives the following exception. Note that, the parsed string does not contain anything related to the optional group clause

    OUTCH Object of type 'sly.parser.parser.ValueOption`1[System.Object]' cannot be converted to type 
    'sly.parser.parser.ValueOption`1[sly.parser.parser.Group`2[netSchematron.XPathToken,System.Object]]'. 
    calling RangeExpr__AdditiveExpr_GROUP-TO[d]-AdditiveExpr? =>  RangeExpr

We have talked about this exception before [in this issue](https://github.com/b3b00/csly/issues/94) however, I can not seem to identify the lexer problem this time.

I think the warnings and the exception are connected.

**Comment by b3b00** [comment]
better tha  to use a * to emulate an option  ? yiu should use a dedicated non terminal with
 someNewNonTerm : TO[d] additiveexxpr

and then your rangexpr rule is

rangexpr : addditiveexpr someNewNonTerm? 

will look later if this is a real bug or simply a bad use.

**Comment by MrMuMu** [comment]
maybe there is missing `ZeroOrOne` clause and `OptionGroupNone`

**Comment by b3b00** [comment]
Hello can you give a test case please ? your repo is not up to date with your error. I can not investigate ....

**Comment by MrMuMu** [comment]
https://github.com/MrMuMu/netSchematron/tree/optionalGroupTest I have pushed a new branch for you to test it. Thank you for your help and time.

**Comment by MrMuMu** [comment]
when I change ? to * on `ComparisonExpr: StringConcatExpr (COMPARATOR StringConcatExpr)?` it works without problem.

When I was debugging, `ComparisonExpr` method was being invoked with ValueOption as none, however it should be passing ValueOption as group and none. So it should understand that if a ValueOption is used with a group and there was no value associated with it, ValueOption group none should be created.

**Comment by b3b00** [comment]
that's not helping.... I do need a minimal test case to understand what's happening. I insist your grammar is too clumsy to be debugged.
please shorten it

**Comment by MrMuMu** [comment]
I have pushed simple minus, plus arithmetic language.

The following rule creates the same problem:

    [Production("XPath: AndExpr (COMPARATOR AndExpr)?")]
    public object XPath(object andExpr, ValueOption<Group<XPathToken, object>> exprList)

if you change it to this:

    [Production("XPath: AndExpr (COMPARATOR AndExpr)*")]
    public object XPath(object andExpr, List<Group<XPathToken, object>> exprList)

you can get the result.

**Comment by b3b00** [comment]
thanks for the test case. i now have a failing unit test (see it on branch bugfix/#104).
I see what hapen. And will try to solve it later.
For now my best proposal is to get rid of the group and use another nonterminal that you can optioned 

XPath: AndExpr newNonTerminal ?
newNonTerminal :  COMPARATOR AndExpr

it's exactly what the group does but it fails on the particular case of an empty option.

**Comment by MrMuMu** [comment]
got it, thank you very much

**Comment by b3b00** [comment]
issue solved with release 2.2.5.1.

Please @MrMuMu  confirm if ok

**Comment by MrMuMu** [comment]
seems to be working thank you very much.
