### ISSUE TITLE
EBNF Parser : End of Stream issues.

### ISSUE THREAD

**Issue by CP3088** [b3b00/csly#141]
Hello,

I am currently making a project in C# for the PineScript language with cSly.
There are many grammar rules for this loosely typed functional language, but I seem to get this error:

`unexpected end of stream. at line 0, column 693. at sly.parser.generator.EBNFParserBuilder`2.<>c__DisplayClass2_0.`

The problem seems to revolve around these Production rules:

`
[Production("fun_def_singleline : id fun_head ARROW [d] fun_body_singleline")]
[Production("fun_def_multiline : id fun_head ARROW [d] LEND? [d] local_stmts_multiline")]
[Production("fun_head : LPAR [d] fun_head_params? RPAR [d]")]
[Production("fun_head_params : id ( COMMA [d] id )*")]
`

I am still working on the class structures, so I am returning nulls for now. This doesn't seem to be the issue, as the exception is for the Parser's initialization... 

When I remove the rules temporarily, this becomes the new error. 

`
unexpected end of stream. at line 0, column 1077.expecting IDENTIFIER, LPAREN,
unexpected end of stream. at line 0, column 1077.
`

What might cause end of stream?

**Comment by CP3088** [comment]
After further debugging, I have learned it is not yet possible to discard [d] an optional or multi terminal/non-terminal. Is this a feature we could expect in the future?

Also, any advice on the BuildResult being okay, but containing a null Lexer?

**Comment by b3b00** [comment]
HI @CP3088 , Sorry for the delay, I should receive email when issue is created but I must have missed it.
So for the first part of your issue, you 're right it is not a supported feature.
I am not planning to support it discardable non terminal as it does not make sense for me. Non terminal are the core structure of a language as opposed to terminal that can be syntactic sugar.
I don't see any relevant use case. Maybe you could add an explanation for your use case ? 

For the second issue I need more detail. Could you send a complete context : lexer (generic or regex based ? ) the parser and the source code that failed to parsed . I don't understand if it happens during the parser initialization or when parsing a pinescript source code.

I would be happy to help you use CSLY.

feel free to complete this issue, I will surely either guide you to use it or solve any issue.

Olivier

**Comment by CP3088** [comment]
Hello,

Thank you for the reply! I have been debugging the project more with the cSly source code and found most of my issues.  On the topic of discarding, I agree that a non-terminal shouldn't be discarded. Most of the confusion came from porting over the grammar from ANTLR v4, which meant I had to remake several rules.

The current issue that has arose is precedence of the production rules. I am using a generic lexer along with your ebnf parser to build the AST by the way. 

My implementation of function calls and variable assignments work well on there own, but when they are both together, variable assignments always take the route of function call rules even though they are setup properly for assignments.

Sorry for the extra issue... haha. Would I be able to email you an example of my problem?

Thanks,
CP3088

**Comment by b3b00** [comment]
Hi @CP3088, I am glad you found your way to solve your problems. By the way yesterday I publish a new release (2.4.1.1) that embed better error reporting during the parser build.
I could have helped you with at least for the first issue.
You can open an issue with your problem, I will look at it soon.

Olivier
