### ISSUE TITLE
EBNF Parser - Issues chaining rules for a param list

### ISSUE THREAD

**Issue by CP3088** [b3b00/csly#145]
Happy Holidays,

I have almost completed a parser using csly. There is one issue I have been facing however.
The scripting language I am mimicking has the ability, like most languages do, to mix default and non-default parameters in function definitions. The key difference is that function calls can mix them as well, assuming the normal non-defaults come first of course.

My function calls work perfectly with only default params, and the same with only non-defaults. However, when I try to mix the two like this:

`|B|plot(c, title='Out')|E|`

I get "unexpected end of stream. at line 0, column 0"

My production rules are as follows:

```
[Production("test : LBEG [d] fun_call LEND [d]")]
public ScriptAST TestStatement(ScriptAST statement)
{
    /* ... */
}

[Production("fun_call : id LPAR [d] ( fun_actual_args )? RPAR [d]")]
public ScriptAST FuncCall(Identifier id, ValueOption<Group<ScriptToken, ScriptAST>> args)
{
    /* ... */
}

[Production("fun_actual_args : kw_args")]
public ScriptAST FuncActualArgsA(ScriptAST kwArgs)
{
    /* ... */
}

[Production("fun_actual_args : pos_args ( COMMA [d] kw_args )?")]
public ScriptAST FuncActualArgsB(Arguments posArgs, ValueOption<Group<ScriptToken, ScriptAST>> kwArgs)
{
    /* ... */
}

[Production("pos_args : arith_expr ( COMMA [d] arith_expr )*")]
public ScriptAST PosArguments(ScriptAST initial, List<Group<ScriptToken, ScriptAST>> subsequent)
{
    /* ... */
}

[Production("kw_args : kw_arg ( COMMA [d] kw_arg )*")]
public ScriptAST KwArguments(Argument initial, List<Group<ScriptToken, ScriptAST>> subsequent)
{
    /* ... */
}

[Production("kw_arg : id DEFINE [d] arith_expr")]
public ScriptAST KeywordArg(Identifier id, ScriptAST expression)
{
    /* ... */
}
```

Both of these work fine...

|B|study("Name or something", overlay)|E|
|B|test(close, 123, open)|E|

But neither of these...

|B|test2(a, b, c=100)|E|
|B|plotshape(data, style=shape.xcross)|E|

I have been debugging this for some time and suspect I need to find another way for csly to accept this behavior. 

Regards,
CP3088

**Comment by b3b00** [comment]
hello @CP3088 , i will look at it very soon

**Comment by b3b00** [comment]
@CP3088 , could you share your lexer and parser to ease debugging please ?

**Comment by b3b00** [comment]
I would do something like this : 
```c#
[Production("fun_call : ID LPAR [d] ( fun_actual_args2 )? RPAR [d]")]
        public object FuncCall(Token<ScriptToken> id, ValueOption<Group<ScriptToken, object>> args)
        {
            return null;
        }

[Production("fun_actual_args2 : args2")]
        public object actargs2(object args)
        {
            return null;
        }

        [Production("args2 : arg (COMMA[d] arg)*")]
        public object argies(object head, List<Group<ScriptToken, object>> tail)
        {
            return null;
        }

        [Production("arg : kw_arg")]
        [Production("arg : arith_expr")]
        public object a(object v)
        {
            return null;
        }
```

Of course with this solution the syntax parsing does not ensure that default parameters only appear at the end of parameter list. Nevertheless you can check this when visiting the AST and throw an exception (or return an error) if needed. 
I dont know the lnaguage you're trying to parse butI think cas like this are related to semantic check more than syntaxic check.

I guess that what you want to parse is not possible to parse with an LL parser (not sure though).
I think more sofisticate parser generator ike ANTLR can manage this kind of grammar but CSLY can't for now. 
Your  case is interresting and I will look at it to maybe find a way to make ti work.

regards

Olivier

**Comment by b3b00** [comment]
Hello @CP3088 ,

I 've just found a better solution. You have to convert some left recursion to right recursions : 

```c#
[Production("fun_actual_args : pos_args kw_args?")]

// for this new rule : 
//   - right recurse in the group
//   - stop 0+ group if a kw_arg is found
[Production("pos_args :  (  arith_expr COMMA [d] )* kw_arg")]

[Production("pos_args :  (  arith_expr COMMA [d] )* arith_expr")]

 [Production("kw_args : ( COMMA [d] kw_arg )* kw_arg ")]

[Production("kw_arg : ID DEFINE [d] arith_expr")]

```

|B|test2(a, b, c=100, d=200)|E| produces following syntax tree :

[<img src="https://user-images.githubusercontent.com/1224790/71616962-1afdb480-2bb9-11ea-8f23-50bf65fcb224.png">](https://user-images.githubusercontent.com/1224790/71616962-1afdb480-2bb9-11ea-8f23-50bf65fcb224.png)



I let you validate this. Please keep me informed of which solution better fits your needs.


Olivier

**Comment by b3b00** [comment]
my testing branch : https://github.com/b3b00/csly/tree/test/left_recursion_CP3088

**Comment by CP3088** [comment]
Thank you so much for these thought out responses! Just another thing that makes your project great. I will implement the right recursive method as it seems like the best option and let you know how it goes from there.

On a side note, I noticed that the parsing takes upwards of 30 seconds for 8 lines of scripting. When this is done, I will need to run approximately 200 lines per script. 

I have about 80 production rules right now, mainly because the | operator doesn't currently work in cSly. From debugging I have found some insights on the causes of this time. Would you care if I made an issue regarding this?

**Comment by b3b00** [comment]
thanks,

go for a performance issue, it's always interesting. If you can join lexer , parser and test case to reproduce.

For the | operator, I thought to make it but did not find  a satisfying way to express the visitor arguments which may vary.
If you have some idea about it feel free to share.

For now I close this issue

**Comment by b3b00** [comment]
to be definitely complete about your grammar problem : the issue comes from the fact that CSLY is better suited for LL(1) grammars as it only looks at one token at a time. rewriting the grammar make it effectively LL(1).
