### ISSUE TITLE
Graphviz Issue

### ISSUE THREAD

**Issue by CP3088** [b3b00/csly#150]
Sometimes when creating the graphviz output, there will be arrows without a destination. 

My grammar is very complex, so that is most likely the issue. However, to prevent this from happening to anyone else, I made an edit in sly/parser/generator/visitor/GraphVizEBNFSyntaxTreeVisitor.cs 

Line 133 in private DotArrow Visit(SyntaxNode<IN> node)

``` c#
children.ForEach(c =>
{
    if (c != null) // Prevent arrows with null destinations
    {
        var edge = new DotArrow(result, c) {
            // Set all available properties
            ArrowHeadShape = "none"
        };    
        Graph.Add(edge);
    }
});    
```

**Comment by b3b00** [comment]
Il faces this issue once or two but ignorés it at that time. You can make a pull request if you want or i'll juste report it myself. As you prefer
