### ISSUE TITLE
Lexical Error '#'

### ISSUE THREAD

**Issue by CP3088** [b3b00/csly#151]
I am having an issue with a generic lexeme. 

Input: #F4C587
Error: Lexical Error : Unrecognized symbol '#'
Lexeme: [Lexeme(GenericToken.Identifier, IdentifierType.Custom, "#", "0-9a-fA-F")] COLOR_LITERAL = 42,

Is this type of character not allowed?

Regards,
CP3088

**Comment by b3b00** [comment]
for Custom identifiers first arguments must be a range and not a single char. so four your special case : 
```c#
[Lexeme(GenericToken.Identifier, IdentifierType.Custom, "#-#", "0-9a-fA-F")] COLOR_LITERAL = 42
```

I will make a fix to warn in case pattern does not match expected format.

**Comment by CP3088** [comment]
With that change, I am still getting this output for my program.

```
|EMPTY|
|B|study('Preprocessor example')|E|
|B|var choice = input(title='Choice', defval='A', options=['A', 'B'])|E|
|B|color = #2E8B57|E|
|EMPTY|

Parser Initialized
Compiling 5 Lines... 7ms
Error
Lexical Error : Unrecognized symbol '#' at  (line 3, column 11).
```

**Comment by b3b00** [comment]
Il can not help without any further contexte. Could you please jiin tour complete lexer configuration ?

**Comment by b3b00** [comment]
I 've made some minimal tests on branch https://github.com/b3b00/csly/tree/bugfix/%23151
You can find : 

- a unit test showing  error management when identifier patterns ar not ranges
- a unit test with a working custom identifier as in your case.

I guess that your problem is some kind of conflicing lexemes in your lexer. Again without the complete lexer I will not be able to help you

**Comment by b3b00** [comment]
One more thing : I guess that your identifier is in fact an RGB color literal.
For this kind of lexeme, I would rather go for [extending the generic lexer](https://github.com/b3b00/csly/wiki/GenericLexerExtension)  instead of using an already eisting lexeme whose intent is not the same. indeed an RGB literal is not an identifier.... it's a literal value.

Unit test ```TestIssue151Extensions``` in GenericLexer (branch bugfix/#151) shows you how to do it.

**Comment by CP3088** [comment]
Very insightful!

I have added the extension as show, yet I am not sure on two points.
How will I incorporate the AddExtension method inside this implemenetation?

```c#
var parser = new PineParser();
var builder = new ParserBuilder<PineToken, PineAST>();
var buildResult = builder.BuildParser(parser, ParserType.EBNF_LL_RECURSIVE_DESCENT, "tvscript");
```

Also, how might I add two hex digits for the optional alpha channel? 

```c#
fsmBuilder.GoTo(GenericLexer<HempToken>.start)
                .Transition('#')
                .Mark("start_color")
                .RepetitionTransition(6, "[0-9,a-f,A-F]")
                .Mark("start_alpha")  // Something like this? 
                .RepetitionTransition(2, "[0-9,a-f,A-F]")
                .End(GenericToken.Extension)
                .CallBack(callback);
```

Will this be optional, or do I need another token?

Thank you very much for all the help.
I have not provided full examples as this project is private in nature, but if there is someway I can share with only you, I will do that.

Regards,
CP3088

**Comment by b3b00** [comment]
First point : for now you can't simply do it. the workaround is o first call the buildParser as you do it. and then rebuild the lexer as shown in the unit test. Then you can reset the lexer doing parser.Lexer = theExtendedLexer.
I will look at a way to integrate it more esaily.

Second point : 
that point is a bit tricky as the fsm builder is not enough documented. In fact even I didn't quite remember about it :)

here is your solution. I also pushed it on the branch.

```c#
fsmBuilder.GoTo(GenericLexer<Extensions>.start)
                    .Transition('#')
                    .Mark("start_date")
                    .RepetitionTransition(4, "[0-9,a-f,A-F]")
                    .End(GenericToken.Extension)
                    .CallBack(callback)
                    .RepetitionTransition(2,"[0-9,a-f,A-F]")
                    .End(GenericToken.Extension)
                    .CallBack(callback);
```

**Comment by b3b00** [comment]
You reported in a previous issue that you encounter performance issues. Did you find any clue about it ? 
Could you tell if the problem comes from the lexer or parser ?
Performance is a real issue for me so I will really appreciate if you can help find performance fixes.

**Comment by CP3088** [comment]
Thank you for the response. I will override the lexer for now.

The performance issues came from my own debugging methods haha. Currently the performance is very fast, but I might have noticed some unnecessary parsing when I last debugged the EBNF parser itself.

When having two rules with the same first token, the parser will fully exhaust any possibility of matching each ones sub rules. A simple variable definition "var_def : id ASSIGN arith_expr" would attempt to match a function call "fun_cal : LPAR [d] ( fun_actual_args )? RPAR [d]" around 500 times.

Without any debug code mixed in, this is very fast, but I might recommend matching the first token, and each sequential terminal until it hits a non terminal. That way "ID ASSIGN" would skip "ID LPAR" immediately? 

Regards
CP3088

**Comment by b3b00** [comment]
I see the point ans will look if it Can be a performance enchantement. Thanks you for tour feedback.
