### ISSUE TITLE
EBNF - Recursive Parsing -> Exponential Performance Losses

### ISSUE THREAD

**Issue by CP3088** [b3b00/csly#152]
Hello, 

I have noticed an issue when it comes to parsing code. 
From the example below, you can see an exponential performance impact:

```
ms	Code
-------------------------------------------------------------------------------------------------
218	|B|xATRTrailingStop = iff(close > val, not val, val)|E|
8077	|B|xATRTrailingStop = iff(close > val, iff(close < val, 0, 1), val)|E|
23659	|B|xATRTrailingStop = iff(close > val, iff(close < val, 0, 1), iff(close < val, 0, 1))|E|
```
The line of code which brought this to my attention was:

```
xATRTrailingStop = iff(close > nz(xATRTrailingStop[1], 0) and close[1] > nz(xATRTrailingStop[1], 0), max(nz(xATRTrailingStop[1]), close - nLoss),
                    iff(close < nz(xATRTrailingStop[1], 0) and close[1] < nz(xATRTrailingStop[1], 0), min(nz(xATRTrailingStop[1]), close + nLoss), 
                        iff(close > nz(xATRTrailingStop[1], 0), close - nLoss, close + nLoss)))
```

Which still did not finish on an 8 core cpu while I slept.
To provide full example, I will need to send you code privately. 

This issue could likely be reproduced easily, but I have 66 production rules and 49 tokens...
I would love to help in anyway I can to improve this.

Regards,
CP3088

**Comment by b3b00** [comment]
Hello @CP3088 ,

Please send me an example of your code : olivier(dot)duhart[at]gmail.com
I 've never faced any particular pef issue with the parser part of CSLY (lexer on the other hand was slow at the beginning)
Maybe the production rule number is too great for CSLY.
I can't say more without a concrete sample.

**Comment by b3b00** [comment]
Hello @CP3088 ,

First thanks for the invitation to your github project.
I've quickly started debugging and I suspect some kind of left recursion in expression parsing. Not sure though as it's a very first debug session.
It would explain your not ending parsing as left recursion is a no way for LL parsers.

- Good news is that any left recursive grammar has a right recursive equivalent.

- Another better solution would be to use another CSLY feature : [expression parsing generator](https://github.com/b3b00/csly/wiki/expression-parsing) that natively generates right recursive grammar with better readability.I would  have little time before monday to give it a try.

- finally  I would evaluate the cost to add left recursion detection both a parser build and runtime.

**Comment by b3b00** [comment]
If appeared that I was right, we have an infinite left recursion in the grammar. You can see it in action in the attached file that contains a stack of the non terminal parsing. You can see an obvious pattern repeating : [stack.txt](https://github.com/b3b00/csly/files/4113228/stack.txt)
I think the best solution is using the[ expression parsing generator](https://github.com/b3b00/csly/wiki/expression-parsing)  I talked about in previous comment.
I do not know the semantic of your language though and I can not easily the precedence and associativity of every operator. 
I guess my help stops here.

Waiting for your answer for any help I could provide or close the issue.

Olivier

**Comment by b3b00** [comment]
I've instrumented CSLY parser to get the parsing stack and it appeared that we effectively have a infinite recursion. 
[stack2.txt](https://github.com/b3b00/csly/files/4113539/stack2.txt)
You can clearly see a repeating pattern in the expression parsing of your grammar.
So it seems your grammar is left recursive (the grammar is too complicated though to tell you where)
As CSLY is a recursive descent parser that only accept LL Grammar. It will end in infinite recursion. see [Why can't a LL grammar be left-recursive?](https://stackoverflow.com/questions/16165352/why-cant-a-ll-grammar-be-left-recursive)

You could try the [expresion parsing generator](https://github.com/b3b00/csly/wiki/expression-parsing) CSLY feature that natively generates right recursion. I can not help you further as I clearly don't know the semantic of your script language, and so the precedence and associativity rules that apply.

Nevertheless this is a good test for CSLY and I will try to add some kind of circuit breaker when detecting such repeating pattern in the parsing stack. Not an easy task .....

As

**Comment by CP3088** [comment]
Thank you for looking at my repo. I have began working on the expression parsing generator, however I fear that some of the syntactical rules  might be lost using this method. 

That horrific chain of expressions you saw on my repo ensured that only identifiers and literals could be used in numerical and logical expressions. Using this convention, how can I prevent someone from multiplying two for statements? 

The end goal is to transpile the script, but would that mean I must perform syntax checking after the parsing?

Regards,
CP3088

**Comment by b3b00** [comment]
Hello,

your language is really strange, I've never seen a language where a for
loop is an expression !
if so then I don't understand why it could not be used in numerical and
logical expressions.
Do you have some script samples that could help me understand the general
structure of the script ?
Then maybe I could help you find a way.

Googling for "pinescript" I found
https://www.tradingview.com/pine-script-docs/en/v4/index.html. Is that your
script ?


Le lun. 27 janv. 2020 à 21:19, Nathan Adams <notifications@github.com> a
écrit :

**Comment by CP3088** [comment]
Ah, sorry I deleted my comment, I had just realized the [Operand] property was what I needed.

Thank you so much for looking over my project! I am not 100% sure on the upgrade for the generic expressions however. I updated the repo, would you mind telling me what is wrong with my implementation?

Also, yes that is the language there. Here are some examples of a couple script features.

Functions: https://www.tradingview.com/wiki/Declaring_Functions
Loops and stuff: https://backtest-rookies.com/2018/01/19/tradingview-create-loop/

Regards,
CP3088

**Comment by b3b00** [comment]
I think you're good.
Only remark, with the last version of csly (2.4.1.5) you can add lexer extensions when building a parser. So instead of 
```c#
var parser = new PineParser();
var builder = new ParserBuilder<PineToken, PineAST>();
var result = builder.BuildParser(parser, ParserType.EBNF_LL_RECURSIVE_DESCENT, "pinescript");

var lexer = LexerBuilder.BuildLexer(new BuildResult<ILexer<PineToken>>(), PineTokenExtensions.AddExtension);
result.Result.Lexer = lexer.Result; // Extending Generic Lexer [ cSLY #151 ]
```

you can write : 

```c#
var parser = new PineParser();
var builder = new ParserBuilder<PineToken, PineAST>();
var result = builder.BuildParser(parser, ParserType.EBNF_LL_RECURSIVE_DESCENT, "pinescript", PineTokenExtensions.AddExtension);
```

Then  you 'll surely have to make some semantic check to make sure that the expression type in a if statement is a boolean. You can check the [While Parser sample](https://github.com/b3b00/csly/tree/dev/samples/while) htat makes some type inference and type checking.

**Comment by b3b00** [comment]
Well in fact there is still some problem as your srcipt sample 
`|B|xATRTrailingStop = iff(close > nz(xATRTrailingStop[1], 0) and close[1] > nz(xATRTrailingStop[1], 0), max(nz(xATRTrailingStop[1]), close - nLoss),iff(close < nz(xATRTrailingStop[1], 0) and close[1] < nz(xATRTrailingStop[1], 0), min(nz(xATRTrailingStop[1]), close + nLoss), iff(close > nz(xATRTrailingStop[1], 0), close - nLoss, close + nLoss)))|E|`

is failing to parse.

I've  simply read your parser. I've no time right now to investigate the parse failure.
Maybe later.

**Comment by CP3088** [comment]
If you could help with that I would be very great full! Thank you for everything you have done so far.
