### ISSUE TITLE
Fix - Error list with no elements

### ISSUE THREAD

**Issue by CP3088** [b3b00/csly#153]
Good afternoon,

RecursiveDecentSyntaxParser.cs on line 434 will sometimes throw a System.InvalidOperationException when the error list is empty. Not sure if that in itself is part of a greater issue, but here is the fix for now.

`greaterIndex = errors.Select(e => e.UnexpectedToken.PositionInTokenFlow).Max();`

Should become

`greaterIndex = errors.Count > 0 ? errors.Select(e => e.UnexpectedToken.PositionInTokenFlow).Max() : 0;`

I am not a GitHub pro, so I will just offer the solution here, haha.

Regards,
CP3088

**Comment by CP3088** [comment]
This seems to root from parsing alternate choice groups, but the solution is still viable without impacting anything else.

**Comment by b3b00** [comment]
thanks for the issue. I 've just correct it right on dev branch
