### ISSUE TITLE
Parsing error does not propagate to caller

### ISSUE THREAD

**Issue by jlittorin** [b3b00/csly#163]
The source string in this test
https://github.com/b3b00/csly/blob/6787d1c4c7b29bba3cbc8a2e37987dfb576a1cd7/ParserTests/GraphVizTests.cs#L73
isn't syntactically correct, there is no PLUS used in the grammar. The error propagates partly to the `syntaxResult` at
https://github.com/b3b00/csly/blob/6787d1c4c7b29bba3cbc8a2e37987dfb576a1cd7/sly/parser/parser/Parser.cs#L99
where `syntaxResult.Errors` is populated but `syntaxResult.IsError == false`

**Comment by b3b00** [comment]
The source "1+1" is ok for the grammar https://github.com/b3b00/csly/blob/dev/samples/SimpleExpressionParser/SimpleExpressionParser.cs

as you can see there is  an PLUS operation defined on visitor method ```BinaryTermExpression```
```c#
 [Operation((int) ExpressionToken.PLUS, Affix.InFix, Associativity.Right, 10)]
        [Operation("MINUS", Affix.InFix, Associativity.Left, 10)]
        public double BinaryTermExpression(double left, Token<ExpressionToken> operation, double right)
        {
```

Maybe you missed the CSLY [expression parsing](https://github.com/b3b00/csly/wiki/expression-parsing
) feature.

Having both an error in errors list and IsError == false is a bit confusing I must admit, but this error is a mere "residue" of a  try for the rule substraction. Keeping track of this error is mandatory to report meaningfull error if completely failing to parse the source as for "1 @ 1" for example : 
```
"Lexical Error : Unrecognized symbol '@' at  (line 1, column 2)."
```

or for "1(1" : 
```
unexpected "(" (LPAREN) at line 1, column 2.
```
Only improvment here could be in the case of "1(1" could be an even better error message like
```
unexpected "(" (LPAREN) at line 1, column 2. expecting "+" , "-" ,"/" or "*"
```
Will investigate it later but it does not seem that easy, though

**Comment by b3b00** [comment]
As you seem really interested in CSLY, may I ask you if you 're thinking to use it and if so for what kind of project ?

**Comment by jlittorin** [comment]
I did look at the expression parsing actually, haven't tried it yet. I think this was a case of sloppy code reading.

As for my use of CSLY, let's move that conversation to another forum. Connecting with you on LinkedIn :)
