### ISSUE TITLE
better error reporting

### ISSUE THREAD

**Issue by b3b00** [b3b00/csly#164]
using [SimpleExpressionParser](https://github.com/b3b00/csly/blob/dev/samples/SimpleExpressionParser/SimpleExpressionParser.cs)

if trying to parse 
```
"1(1" 
```
which is lexing ok
we get the following error message :
```
unexpected "(" (LPAREN) at line 1, column 2.
```

Even if it can help solving the parsing issue a better error message would be 
```
unexpected "(" (LPAREN) at line 1, column 2, expecting "+" (PLUS) , "-" (MINUS) "/" (DIVIDE) or "*" (TIMES)
```

**Comment by CP3088** [comment]
Really small request
LexerBuilder.cs on lines 256-259

```c#
catch (Exception e)
{
    result.AddError(new InitializationError(ErrorLevel.FATAL, e.Message));
}
```

Use derived class

```c#
catch (Exception e)
{
    result.AddError(new LexerInitializationError(ErrorLevel.FATAL, e.Message));
}
```

**Comment by b3b00** [comment]
@CP3088 , could send a PR please, would be easier ...

**Comment by b3b00** [comment]
@CP3088 I've tried your fix, but it does not actually solve the issue I describe above. Of course it is better but does not solve the issue.

**Comment by CP3088** [comment]
Sorry, only meant it as a small change. Currently working on error reporting for my whole program right now, so if I can make anything useful there will be a PR :)
