### ISSUE TITLE
Lexer cant recognize if

### ISSUE THREAD

**Issue by Sl4vP0weR** [b3b00/csly#166]
Enum:

[Lexeme("(if)")] IF,

string for lexer:

if a == 0
{
return a;
}

error: Lexical Error : Unrecognized symbol 'i' at  (line 1, column 1).

**Comment by b3b00** [comment]
That's a bit short !
Which lexer do you use (regex or generic) ? 
Assuming your code, I guess regex. In this case the correct regex should be :
```
[Lexeme("if")] IF,
```
no paranthesis 
try this or switch to generic lexer : 
```
[Lexeme(GenericToken.Keyword, "if") IF,
```

When issuing please provide as much context as possible ! I have to make too much assumption to reply.

**Comment by Sl4vP0weR** [comment]
> [Lexeme(GenericToken.Keyword, "if") IF,

Dont works

**Comment by b3b00** [comment]
please @Sl4vP0weR provide context ! 
Just saying "don't work" won't help. 
Have you tried the regex "if" ? You can't mix generic lexeme with regex lexemes maybe it's your case.

Only if you provide the full lexer I can help

**Comment by Sl4vP0weR** [comment]
public class SyntaxTree
    {
        public SyntaxTree(string code)
        {
            GenericLexer<Token> l = new GenericLexer<Token>();
            var tokenizeRes = l.Tokenize(code);
            if(tokenizeRes.IsOk)
            {
                var tokens = tokenizeRes.Tokens;
                ParserBuilder<Token, AST> pBld = new ParserBuilder<Token, AST>();
                tokens.ForEach(t => Console.WriteLine(t));
                var p = pBld.BuildParser(new CParser(), ParserType.EBNF_LL_RECURSIVE_DESCENT, "statement").Result;
                var parseResult = p.Parse(code);
                if(parseResult.IsOk)
                {
                    Scope currentScope = parseResult.Result.CompilerScope;
                    while (currentScope != null)
                    {
                        LogScope(parseResult.Result.CompilerScope);
                    }
                }
                else if(parseResult.IsError)
                {
                    parseResult.Errors.ForEach(e => Console.WriteLine(e));
                }
            }
            else if(tokenizeRes.IsError)
            {
                Console.WriteLine(tokenizeRes.Error);
            }
        }
        private void LogScope(Scope scope)
        {
            Console.WriteLine(scope.Id);
            foreach(var scopeChild in scope.Scopes)
            {
                LogScope(scopeChild);
            }
        }
    }

**Comment by Sl4vP0weR** [comment]
![image](https://user-images.githubusercontent.com/42337892/76980096-b9f1ab80-6973-11ea-9d2a-f0de6d3afcc8.png)

**Comment by b3b00** [comment]
What I was asking for is your lexer enum that contains :
```
[Lexeme("if")] IF,
```

**Comment by Sl4vP0weR** [comment]
Lexical Error : Unrecognized symbol 'i' at  (line 0, column 0).

**Comment by Sl4vP0weR** [comment]
public enum Token
    {
        EOF,

        [Lexeme(">")] GREATER,

        [Lexeme("<")] LESSER,

        [Lexeme(">=")] GREATEROREQ,

        [Lexeme("<=")] LESSEROREQ,

        [Lexeme("==")] EQUALS,

        [Lexeme("!=")] NEQUALS,

        [Lexeme(@"\.")] DOT,

        [Lexeme(@"\+")] PLUS,

        [Lexeme(@"\-")] MINUS,

        [Lexeme(@"\*")] TIMES,

        [Lexeme(@"\/")] DIVIDE,

        [Lexeme(@"\{")] LPAREN,

        [Lexeme(@"\}")] RPAREN,

        [Lexeme(@"\[")] LBRACKET,

        [Lexeme(@"\]")] RBRACKET,

        [Lexeme(@"\(")] LCBRACKET,

        [Lexeme(@"\)")] RCBRACKET,

        [Lexeme("[a-zA-Z]+")] IDENTIFIER,

        [Lexeme("\"[^\"]*\"")] STRING,

        [Lexeme("[0-9]+")] INT,

        [Lexeme("[ \\t]+", true)] WS,

        [Lexeme(@"[\n\r]+", true, true)] EOL,

        [Lexeme("if")] IF,

        [Lexeme("else")] ELSE,

        [Lexeme("while")] WHILE,

        [Lexeme("break")] BREAK,

        [Lexeme("true")] TRUE,
        [Lexeme("false")] FALSE,
        [Lexeme("!")] NOT,

        [Lexeme("&")] AND,

        [Lexeme("|")] OR,
        [Lexeme("(return)")] RETURN,
    }

**Comment by b3b00** [comment]
your lexer is ok. I have no problem lexing "if 1 == 1"
![image](https://user-images.githubusercontent.com/1224790/76981679-39af5400-693b-11ea-9561-a1210f0e4642.png)

Well you lexer is almost ok.
You have a conflict between 
```
[Lexeme("[a-zA-Z]+")] IDENTIFIER
```
and 
```
[Lexeme("if")] IF,
```
in fact with all the keywords (if else break ...)
indeed the lexeme IDENTIFIER will try to match before all other keywords and will match so you'll never have a IF or ELSE ... lexeme

To solve this the best solution is to switch to [generic lexer](https://github.com/b3b00/csly/wiki/GenericLexer). It's way more performant and ,to my opinion at least, easier to configure.

**Comment by Sl4vP0weR** [comment]
I'm copied identifier from ur WhileToken, idk why its wrong, lmao
Just a newbie in lexers and parsers :/

**Comment by b3b00** [comment]
I missed one thing :

you instantiate the lexer this way : 
```
GenericLexer<Token> lexer = new  GenericLexer<Token>()
```
that is not the correct way. it should be 
```
var lexRes = LexerBuilder.BuildLexer<Token>(); 
```

lexerBuilder will choose between regex or generic lexer acording to lexeme used.

**Comment by b3b00** [comment]
for regex lexer, order is important and you reorder lexeme in yours.

**Comment by Sl4vP0weR** [comment]
Well, nothing is in console output, why ?

**Comment by b3b00** [comment]
I dont understand your question

**Comment by Sl4vP0weR** [comment]
![image](https://user-images.githubusercontent.com/42337892/76982824-67b28980-6977-11ea-902c-d8aeffebb773.png)
But console is clear

**Comment by b3b00** [comment]
well have you tried to debug tokens variable length ? 
have you tried to inspect it while debugging ?
I cant say more

**Comment by Sl4vP0weR** [comment]
tokenizeRes is null

**Comment by b3b00** [comment]
so 
```
if (tokenizeRes.IsOk) 
```
should raise a nullreferenceexception and so application will exit.

I cant see any reason why it would work for me and fails for you.

**Comment by b3b00** [comment]
What version of sly do you use ? 
What .net framework do you use ? .net framework or .net core ?

**Comment by Sl4vP0weR** [comment]
Mb cuz u are using Core ?

**Comment by Sl4vP0weR** [comment]
We are thinking about the same ;D

**Comment by b3b00** [comment]
what is the value of the code variable ?

**Comment by Sl4vP0weR** [comment]
I dont understood u

**Comment by Sl4vP0weR** [comment]
I'm using .NET Framework 4.6.1

**Comment by b3b00** [comment]
I was aking for the code you are trying to lex.
nevermind I 've just tried a new .net framework 4.6.1 and it works.
Maybe you should try to clone my repo and try to debug a sample just to find your way.

**Comment by Sl4vP0weR** [comment]
Can I ask u to give me ur Discord ?

**Comment by Sl4vP0weR** [comment]
Or add me, I need to talk with u personal
Sl4vP0weR#4178

**Comment by b3b00** [comment]
I have no discord and dont want to have.

**Comment by Sl4vP0weR** [comment]
My problem not solved
I'm tried all your offers, doesn't helped me

**Comment by b3b00** [comment]
@Sl4vP0weR your problem may not be solved butyou keep on not providing enough context. how can i help with this ?
last try : post a zip of your project and provide :
- OS version
- .net frameworks installed
- dev Environment used
- anything else that may be related

**Comment by Sl4vP0weR** [comment]
Nevermind I solved my problem, Microsoft.CodeAnalysis

**Comment by b3b00** [comment]
@Sl4vP0weR  i would have tell you to use this if you have provided enough context...... csly is not made for full featured language as i state it in the readme
