### ISSUE TITLE
Generic Lexer: Negative Integer and Special Doubles

### ISSUE THREAD

**Issue by CP3088** [b3b00/csly#174]
Hello,

I have been making great progress on my scripting language. Today I realized that a negative number would tokenize as a MINUS and an INT. Another thing I am looking for is adding shorthand and exponents to my double literals. For instance: 

0.5
.75
7.245E-5
1.83857e+5

How would I go about extending the generic lexer for these two lexems?

CP3088

**Comment by CP3088** [comment]
I am going to play around with extending the generic lexer. If I find a good solution I will make a PR with either updated or new GenericTokens

Hope all is well my friend.

**Comment by b3b00** [comment]
@CP3088 ,

- negative integers or double : as MINUS is a lexeme (at least for substractions) you can't have negative number lexemes, it can only be an expression.
- special doubles : as your need is specific (this can be discussed of course) I would rather use [generic lexer extension](https://github.com/b3b00/csly/wiki/GenericLexerExtension).  Once you have it working with a generic lexer extension it would be straightforward to make it CSLY native.

**Comment by b3b00** [comment]
somethin like this for exponents :

```c#
// enum lexer
public enum DoubleExponent {
        [Lexeme(GenericToken.Double)]
        DOUBLE = 1,
        
        [Lexeme(GenericToken.Extension)]
        DOUBLE_EXP = 2
    }

// extension method
private static void AddExponentExtension(DoubleExponent token, LexemeAttribute lexem, GenericLexer<DoubleExponent> lexer) {
            if (token == DoubleExponent.DOUBLE_EXP) {

   	
                // callback on end_exponent node 
                NodeCallback<GenericToken> callback = (FSMMatch<GenericToken> match) => 
                {
                    string[] items = match.Result.Value.Split(new[] {'e', 'E'});
                    double radix = 0;
                    double.TryParse(items[0].Replace(".",","), out radix);
                    double exponent = 0;
                    double.TryParse(items[1],out exponent);
                    double value = Math.Pow(radix, exponent);
                    match.Result.SpanValue = value.ToString().AsMemory();
                    
                    match.Properties[GenericLexer<DoubleExponent>.DerivedToken] = DoubleExponent.DOUBLE_EXP;
                    return match;
                };
   	
                var fsmBuilder = lexer.FSMBuilder;

   	
                fsmBuilder.GoTo(GenericLexer<DoubleExponent>.in_double) // start a in_double node
                    .Transition(new char[] {'E','e'}) // add a transition on '.' with precondition
                    .Transition(new char[]{'+','-'})
                    .Mark("start_exponent_val")
                    .RangeTransitionTo('0','9',"start_exponent_val") // first year digit
                    .Mark("end_exponent")
                    .End(GenericToken.Extension) // mark as ending node 
                    .CallBack(callback); // set the ending callback
            }
        }

// lexer construction : 
private static void TestDoubleExponent()
        {
            var lex = LexerBuilder.BuildLexer<DoubleExponent>(AddExponentExtension);
            if (lex.IsOk)
            {
                var one = lex.Result.Tokenize("2.0E+2");
                ;
                var two = lex.Result.Tokenize("4.0e-2");
                ;
            }
        }
```

this only works for double exponentiation. i.e. ```2e+8 ``` will not e lexed correctly if at all. if you want  integer exponentiation you would have to complete the extension method.

**Comment by CP3088** [comment]
Very insightful! I have been working on it as one extension NUMERIC_OR_DASH, which I planned on using the callbacks to select the correct token. My current struggle is trying to transition e or E and - or +

```c#
.Transition(new char[] {'E','e'}) // add a transition on '.' with precondition
.Transition(new char[] {'+','-'})
```

The above gives me "Argument 1: cannot convert from 'char[]' to 'char'" as there is no overload on your dev branch. I also noticed that the Wiki documentation shows the ability to use a predicate type function, but the current branch only has overloads for TransitionPrecondition

This is my extension thus far.

```c#
                case PineToken.NUMERIC_OR_DASH:
                    var nod_callback = GetCallback(HempToken.NUMERIC_OR_DASH);

                    fsmBuilder.GoTo(start)
                        .AnyTransition('-') // Allows for optional dash in numerics!
                        .End(GenericToken.Extension)
                        .CallBack(nod_callback)

                        .Mark("in_int")
                        .RangeTransitionTo('0', '9', "in_int")
                        .End(GenericToken.Extension)
                        .CallBack(nod_callback)

                        .Transition('.')
                        .Mark("in_double")
                        .RangeTransitionTo('0', '9', "in_double")
                        .End(GenericToken.Extension)
                        .CallBack(nod_callback)

// WIP

                        .Transition(new char[] { 'E', 'e' }) // Error
                        //.MultiRangeTransitionTo("start_exp", ('e', 'e'), ('E', 'E'))
                        //.MultiRangeTransitionTo("start_exp", ('-', '-'), ('+', '+'))
                        .Mark("in_exp")
                        .RangeTransitionTo('0', '9', "in_exp")
                        .End(GenericToken.Extension)
                        .CallBack(nod_callback) ;
                    break;
```

**Comment by b3b00** [comment]
Sorry I forgot to push to dev the Transition(char(]) that I 've add for your purpose. It 's on dev branch now you can try it. I've even pushed the sample in Program.cs

**Comment by CP3088** [comment]
Thank you very much! I am now passing all my tests except one. 

```c#
                case PineToken.NUMERIC_OR_DASH:
                    var nod_callback = GetCallback(HempToken.NUMERIC_OR_DASH);

                    fsmBuilder.GoTo(start)
                        .AnyTransition('-')
                        .End(GenericToken.Extension)
                        .CallBack(nod_callback)

                        .Mark("in_int")
                        .RangeTransitionTo('0', '9', "in_int")
                        .End(GenericToken.Extension)
                        .Mark("end_num")
                        .CallBack(nod_callback)

                        .Transition('.')
                        .Mark("in_double")
                        .RangeTransitionTo('0', '9', "in_double")
                        .Mark("end_num")
                        .End(GenericToken.Extension)
                        .CallBack(nod_callback)

                        .GoTo("end_num")
                        .Transition(new char[] { 'e', 'E' })
                        .Transition(new char[] { '-', '+' })
                        .Mark("in_exp")
                        .RangeTransitionTo('0', '9', "in_exp")
                        .End(GenericToken.Extension)
                        .CallBack(nod_callback);
                    break;
```

The only number left to parse is 1e+6 (1000000), but it won't return back to the int's node. Giving me: NUMERIC_OR_DASH[1], ID[e], PLUS[+], NUMERIC_OR_DASH[6]

It works of course for 1.0e+6 and .4e-3 and even -.4e-3 (negated perfectly for the Token.DoubleValue)

I have been teaching myself more about FSM's in the past week, and think this should be possible.
On another note, I really want to help out the cSly project and extend this to native. Would this method of one catch-all being split into the correct token later be something you are interested in?

**Comment by b3b00** [comment]
If you get a clean solution for tout kind of token go ahead ans sens me a PR. I will be glad to add this kind of little feature.

**Comment by CP3088** [comment]
Sounds good. One last request would be  .AnyTransition() and .AnyTransitionTo() to also accept a char array. After that I think I can make it work!

**Comment by b3b00** [comment]
anyTransition is made to accept any char , so I won't make sens to make it accept only a subset of char.
Werent you speaking about ExceptTransition, if so it already accepts a char array.

**Comment by mcclown** [comment]
Sorry to chime in but I'm also hitting this same issue with a language I'm trying to parse.

When I try this code it's calculating the exponential incorrectly. For 5.0e+9, ie. 5,000,000,000, or 5(10^9), it's actually calculating 1.953125E+15, which is (5 * 10)^9.

I made the changes below, to the callback and now it works as I would expect it to.

```C#
                NodeCallback<GenericToken> callback = (FSMMatch<GenericToken> match) =>
                {
                    string[] items = match.Result.Value.Split(new[] {'e', 'E'});
                    double number = 0;
                    double.TryParse(items[0], out number);
                    double exponent = 0;
                    double.TryParse(items[1], out exponent);
                    double radix = 10.0;
                    double value = number * Math.Pow(radix, exponent);
                    match.Result.SpanValue = value.ToString().AsMemory();

                    match.Properties[GenericLexer<DoubleExponent>.DerivedToken] = DoubleExponent.DOUBLE_EXP;
                    return match;
                };

```

If this is added as a feature it would be good if it can be configured, to support more than just @CP3088 requirements. My language would accept all of the following inputs. (both as lower case and upper case 'e'). This is as per C# language spec as well.

5.0e+9
5.0e-9
5.0e9
5e+9
5e-9
5e9

**Comment by b3b00** [comment]
@CP3088 @mcclown , I don't think that double and int exponents are a must have feature. 
The lexer extension is a way to solve the issue and @mcclown  as you correct it it works better.
I dont see right know a way to make it CSLY native without cluttering the lexer configuration.

furthermore I think it would intoduce language specificities in CSLY core engine, which I don't want to keep CSLY as generic as possible.

So for now I wille not investigate on it.

**Comment by b3b00** [comment]
nevertheless, feel free to propose a PR and I will be glad to look at it and restudy my current thinking.

**Comment by mcclown** [comment]
I agree, as long as the new code to allow a char array to be used with Transition, is available, then I think this can be handled with an extension/callback
