### ISSUE TITLE
BuildParser  doesn't use buildExtensions parameter for EBNF grammars

### ISSUE THREAD

**Issue by mcclown** [b3b00/csly#180]
The following code fails to execute the buildExtensions callback.

```C#
            var parserInstance = new Parser();
            var builder = new ParserBuilder<Token, Model.Root>(); 
            var parser = builder.BuildParser(parserInstance, ParserType.EBNF_LL_RECURSIVE_DESCENT, "sequence", UserCreatedExtension).Result;
```

I've got a fix built already, I'll open a pull request and link it back to this ticket.

**Comment by mcclown** [comment]
Ah, it looks like this is fixed in dev and the current release but not in master.

I'll close this now. @b3b00 Are you doing releases from the dev branch, rather than master?

**Comment by b3b00** [comment]
Yes, CI (appveyor and now github actions) are releasing on version changes on dev branch. I will merge dev on master soon
