### ISSUE TITLE
Use arabic keywords

### ISSUE THREAD

**Issue by maelmahdy** [b3b00/csly#187]
I'm evaluating the library by building a very simple DSL but one of the requirements is to use arabic keywords
When I use arabic letters I get the below error:
Lexical Error : Unrecognized symbol 'ا' at  (line 0, column 0)

Is there any way to support arabic keywords?

**Comment by b3b00** [comment]
Hello, I have no idea how to test arabic symbols (or cyrillic, or kanji....) 
Could you provide a sample lexer, parser and test case ?

**Comment by b3b00** [comment]
Maybe this issue is a problemof encoding between your lexer/parser definifition and your source code ?

**Comment by b3b00** [comment]
hello better reading your issue, I guess I figure what is happening. You're using a generic lexeme to match identifiers. Something like 
```
 [Lexeme(GenericToken.Identifier, IdentifierType.Alpha)]
 ID
```

if you use predefined identifier types :

- IdentifierType.Alpha
- IdentifierType.AlphaNumeric
- IdentifierType.AlphaNumericDash

then indeed you can not parse arabic language. Nevertheless it may work if you use the IdentifierType.Custom specifying leading char range  and traingling chars range.
I don't know arabic alphabet so I can not be sure it will solve your issue but you may give it a try.

**Comment by maelmahdy** [comment]
@b3b00 Thanks for your reply,
Yes, it worked fine by using IdentifierType.Custom, thank you!

**Comment by b3b00** [comment]
@maelmahdy  thanks for your feedback. Glad to learn that CSLY can manage alphabet other than latin
