### ISSUE TITLE
Is the project still alive?

### ISSUE THREAD

**Issue by maelmahdy** [b3b00/csly#188]
Hello Dears,
Do you plan to support the project ?
because it seems abandoned and no one is going to support it

I was planning to use it in some enterprise-level projects but I switched to another library due to lack of support however I find csly is amazing if it got enough support.

I hope you're really planning to continue & support this great project.

**Comment by b3b00** [comment]
yes indeed it 's still alive , I've juste not checked issues for the last days. i am looking at them

**Comment by b3b00** [comment]
May I ask which library you choosed ? sorry for the delay even though you can understand CSLY is not my full time job.

**Comment by maelmahdy** [comment]
@b3b00 I switched to [Sprache](https://github.com/sprache/Sprache) but to be honest, I find csly more appealing to me; just with some more support it'll be the #1 choice for huge number of developers.

**Comment by b3b00** [comment]
@maelmahdy again sorry for the delay. I take care of my project and you can look at past issue where issuer thanked me to quickly provide an answer. 
Spache is a good choice though, a great library. I just can't groke the whole thing with parser combinators

**Comment by maelmahdy** [comment]
@b3b00 I'm really happy to know that :)
