### ISSUE TITLE
Optional tokens causes parser to fail

### ISSUE THREAD

**Issue by maelmahdy** [b3b00/csly#190]
Hello again :)

I'm trying to write a very simple dsl for evaluation purposes and I've the below production rule:
```
[Production("boolean: NOT? [TRUE | FALSE | YES | NO]")]
        public ScriptExecutionResult BooleanValue(Token<GrammarToken> notToken, Token<GrammarToken> valueToken, ScriptContext context)
```

When I try to parse "not true" expression using EBNF_LL_RECURSIVE_DESCENT parser, I get the below message:
unexpected "not" (NOT) at line 0, column 0.

When I remove "?" from the production rule, it works fine so the problem is with the optional modifier.

**Comment by b3b00** [comment]
I will look at it as soon as i start m'y day.

**Comment by b3b00** [comment]
issue fixed. nuget 2.6.0.3 will be available soon when github actions workflow ends

**Comment by b3b00** [comment]
@maelmahdy , could you confirm issue is solved ? if so you can  close the issue

**Comment by maelmahdy** [comment]
@b3b00 Thank you so much, it's working fine now.
