### ISSUE TITLE
EBNF: Add support for choices in groups

### ISSUE THREAD

**Issue by gruntmaster1** [b3b00/csly#205]
When using the following rule:
```
[Production("arguments: LPAREN [d] [expression | expression_type] (COMMA [d] [expression | expression_type])* RPAREN [d]")]
```
I get the following error:
```
PARSER_UNKNOWN_ERROR: rule error [arguments: LPAREN [d] [expression | expression_type] (COMMA [d] [expression | expression_type])* RPAREN [d]] : unexpected "(" (LPAREN) at line 0, column 53.
```

Looking at the grammar of the EBNF, it looks like groups only support identifier and discard tokens. It is easy to solve the error with a new rule, but it would be nice to have the option.

**Comment by b3b00** [comment]
Siret for thé delay, i will look at it

**Comment by b3b00** [comment]
I added support for choices in groups : [groups and sub-rules](https://github.com/b3b00/csly/wiki/EBNF-parser#groups--sub-rules)
you  can test it with release 2.6.2 (nuget available).
I close the issue but feel free to reopen and comment if you want

**Comment by b3b00** [comment]
@gruntmaster1 are you ok with the fix ? please answer
