### ISSUE TITLE
How to parse hexadecimal numbers?

### ISSUE THREAD

**Issue by znakeeye** [b3b00/csly#209]
E.g. `0xff`?

Token:
```c#
[Lexeme(GenericToken.Identifier, IdentifierType.Custom, "0x", "0-9A-Fa-f")]
HEX,
```

Rule:
```c#
[Production("number : HEX")]
public string Number(Token<MyToken> number) => number.Value;
```

Parser:
```c#
var builder = new ParserBuilder<MyToken, string>();
var parser = builder.BuildParser(myParser, ParserType.EBNF_LL_RECURSIVE_DESCENT, "number");
var result = parser.Result.Parse("0xff");
```

**Expected:** `"0xff"`
**Actual:** `"0"`

It seems the first pattern can only be a single character for custom identifiers? If I move the `x` to the second pattern, it will match the whole hexadecimal numbers, but then it will also match incorrect values like `0xffxxx`. Ideas?

**Comment by b3b00** [comment]
using Identifier to parse hex number would be a bad way, as this is thought to parse ..... well , identifiers.
If you use the generic lexer, you 'll have to use the [Generic Lexer extension](https://github.com/b3b00/csly/wiki/GenericLexerExtension). You can have a look at issue #174 where I explain a similar use case for double with exponent.

And for the custom identifier, first pattern can be : 

- a single char
- or a set of patterns like a-z. So it may work using "0-0x-x" but i would definitely adive to use a generic lexer extension as if you also want to use identifier for identifiers it will mess. And chances exist that hex number would be considered as identifiers and parser would be lost.

Please answer to let me know if this answer is ok for you

**Comment by znakeeye** [comment]
Thanks! Solved it using a generic lexer extension.
