### ISSUE TITLE
Best approach to parse/split complex tokens?

### ISSUE THREAD

**Issue by znakeeye** [b3b00/csly#213]
Using a generic lexer. What is the best approach to handle complex tokens, that themselves may contain tokens? Like some advanced [javadoc comments](https://ase.in.tum.de/paid.globalse.org/PAID/Misc-Documents/javadoc/howto.html) but not nearly as complex. In fact, the grammar I'm aiming at is quite simple, except for this special token... I've thought about this problem for two weeks now, and I'm worried that `csly` is not capable of elegantly handling this case.

I'm facing a problem where a line starting with a specific token logically represents a token or several tokens. Similar to the javadoc thing, but not multi-line. E.g.

```
/* Start and end token, but here we can <b>add</b> other tokens as well. */
OtherToken
/* Here is a PATH token. */
```

What's the best approach here? Ideally, I would want to write an extension that can **split** the result in multiple tokens. From what I can tell, this is not supported.

Ideas? Should I parse the entire line as a "line token" and then add some primitive parser logic when building the AST? Or should I introduce `WS` for whitespaces, and bloat the entire grammar with whitespace stuff?

**Comment by b3b00** [comment]
Hello @znakeeye,

Bloating grammar with WS would definitly be a bad idea for parser readability.Chnaging this behavior to stop lexing when  1 token have been found, would lead to strange lexing. Exemple, using this very simple lexer   : 
```c#
public enum Issue213
    {
       [Lexeme(GenericToken.Identifier, IdentifierType.AlphaNumeric)]
        IDENTIFIER = 1,

        [Lexeme(GenericToken.Int)] 
        INTEGER = 2,

        [Lexeme(GenericToken.SugarToken, "=")] 
        EQUAL = 3
    }
```
using this lexing to lex ```myIdentifier1 = 1024``` would be expected to produce : 
```<IDENTIFIER>("myIdentifier1") <EQUAL>("=") <INTEGER>("1024")```
but in fact will resolve to 
```<IDENTIFIER>("myIdentifier") INTEGER("1") <EQUAL>("=") <INTEGER>("1024")```
That is not a good thing.

So for now the only thing I could think of is manage it at parser level spliting the comment line to produce the desired AST.

Other approach would be to exclude extensions from the "largest token possible" principle, but I dont know if it's quite feasible and your use case seems to be such a limit use case that I am not sure to change a native behavior so heavily.

**Comment by b3b00** [comment]
@znakeeye maybe telling me your global purpose would help me guide you. If your project is not that secret would you mind share grammar and lexer as long as general idea behind them ?

**Comment by b3b00** [comment]
@znakeeye 
One more thing.
I dont know of any grammar that have this particular need. For the javadoc exemple I think they manage it chaining 2 parsers : 

1. the first parses the general java grammar (classes, methods,  statements)
2. the second parses the comments to extract javadocs. More or less what you want to do using a split but maybe more elegant and easier to extend. You could try this way building a comment parser and pasing it to the global parser.

for approach 2 you could not use [Comment] attributes has comment are discarded by default to not cluttered the grammar.Nevertheless this could be easily change at lexer level, something like this : 
```c#
[MultiLineComment(start:"/*", end:"*/",doNotIgnore:true)]
        JAVADOCCOMMENT = 1,
```

this could be interresting for future use case. So we could give it a try if you agree to clone my repo and link it to your project on a dedicated branch to validate the approach.

**Comment by b3b00** [comment]
@znakeeye , please answer if you solved your problem with new cly version , or if you need more help

**Comment by znakeeye** [comment]
Thanks for your quick response. Will try your new code.
I believe having two parsers is the right approach. Not sure how to incorporate such a pattern though. Ideally, any errors produced in the inner parser would be produced/accessible by the outer parser. Maybe there is a token attribute for this?

As for the havadoc comment, such a token could be parsed with an extension as well. Do you think a generic doNotIgnore setting is motivated?

**Comment by b3b00** [comment]
Hello @znakeeye , I am not sure what about your are thinking saying ` Ideally, any errors produced in the inner parser would be produced/accessible by the outer parser. Maybe there is a token attribute for this?` .
Do you suggest having something like 
```c#
[MultiLineComment("/*","*/",doNotIgnore:true, useParser:typeof(MyCommentParser)]
PARSED_COMMENT
```
If so i dont think that it would be a good idea as it would introduce a dependency between lexer and parser.
Writing this a better way would be to annotate the token in the production rule : 
```c#
[Production("id : COMMENT[parsedWith:MyCommentParser] ID")]
// Token for COMMENT is replace by parser output type : DotNotIgnore.
public DoNotIgnore CommentedId(DoNotIgnore  comment, Token<DoNotIgnoreCommentsToken> token)
 {
// do something clever here
}
```

this could be a great way to split a complex grammar in many parsers. But we need to make every parser to have the exact same type (```Parser<DoNotIgnoreCommentsToken,DoNotIgnore>``` in my exemple).
In fact I thought about somethin like this lany time without founding inspiration to do it. Now I have a good way to do it and will try to implement it (at least as en experimental feature)

Thanks for using CSLY and helping me improve it.

**Comment by znakeeye** [comment]
Good analysis! That seems like a very good solution, and would definitely solve the problem I encountered!

**Comment by b3b00** [comment]
Well indeed that would solve it, but I still have to rethink about it. 
Only adding it on a Comment token is a bit too restrictive. I think most of the case can be achieve other ways. I have to recheck your use case it may exist a more csly canonical approach
