### ISSUE TITLE
Subparser feature

### ISSUE THREAD

**Issue by b3b00** [b3b00/csly#215]
A interresting feature would be to be able to compose parsers using special attributes in production rules:
```
 public enum EToken
    {
        [Lexeme(GenericToken.Identifier, IdentifierType.AlphaNumeric)]
        ID = 1,
        
        [Lexeme(GenericToken.Int)]
        INT = 2
    }

    public class Parser
    {
        [Production("main : ID subRuleParser INT")]
        public object Main(Token<EToken> id, object subParsed, Token<EToken> integer)
        {
            // do something here
            return null;
        }
        
        // declare use of SubParserType class as a subParser
        [Production("subRuleParser : SubParser(SubParserType) ")]
        public object subParsed(object value)
        {
            return value;
        }
    }

    public class SubParserType
    {
        [Production("submain : ID ")] // root rule
        public object SubMain(Token<EToken> id)
        {
            return id.Value;
        }        
    }
```

All the parsers constituing the global parser mus have the exact same time (```Parser<ETOken,object>``` in above exemple)
Instead of defining a dedicated rule for subparser it could be defined inside the production rule

```c#
[Production("main : ID subRuleParser[SubParser(SubParserType) INT")]
        public object Main(Token<EToken> id, object subParsed, Token<EToken> integer)
        {
            // do something here
            return null;
        }
```
this notation is terser but first one allow reuse if necessary (bot could exist at the same time)

**Comment by znakeeye** [comment]
How about an extra attribute on the parser itself? I believe it makes sense to have a sub-parser for all instances of a token.
```c#
[SubRuleParser("ID", typeof(SubParser))] // Or maybe (int)EToken.ID?
public class Parser
```

**Comment by b3b00** [comment]
Rethinking about it  I am not convinced that a subparser should be bound to a token. there is use cases where subparser may want to parse larger thing than a mere single token. We could think abuot linq expressions for instance in C#.

@znakeeye , about your original issue #213 I guess the only way is to create a dedicated parser to parse the comment token as I suggested it.

And reading about how other parser generators manage theses kind of edge case I 've discovered the antlr channel concept (I guess that it is used for java's javadoc or c#'s xmldoc.

**Comment by znakeeye** [comment]
Yes, the channel concept is indeed a good source of inspiration.

I'll try to come up with a more detailed grammar example to pinpoint the problem.

**Comment by b3b00** [comment]
@znakeeye I have a branch with a experimental channels implementation.
Tokens are stored in different channels : 

- 0 : the main channel, these tokens are accesible by the parser
- 1 : whitespace tokens, these tokens are hidden
- 2 : comment tokens, these tokens are hiddent
- xxx : you can use other channel ids if you want for special purpose.

hidden tokens are accessible through Token.Previous(int channelId) and Token.Next(int channelId)


 Here is the basic test case : 

```c#
[Lexer(IgnoreWS = true, IgnoreEOL = true)]
    public enum DoNotIgnoreCommentsTokenWithChannels
    {
        [MultiLineComment("/*","*/")] // COMMENTS are stored in channel 2
        COMMENT = 1,

        [Lexeme(GenericToken.Identifier, IdentifierType.AlphaNumeric)]
        ID = 2,
        
        [Lexeme(GenericToken.Double, channel:101)] // double token are redirected to channel 101
        DOUBLE = 3
    }

public class DoNotIgnoreCommentsWithChannelsParser
    {
        [Production("main : id *")]
        public DoNotIgnore Main(List<DoNotIgnore> ids)
        {
            return new IdentifierList(ids);
        }

         [Production("id : ID")]
        public DoNotIgnore SimpleId(Token<DoNotIgnoreCommentsTokenWithChannels> token)
        {
            // get previous token in channel 2 (COMMENT)
            var previous = token.Previous(Channels.Comments);
            string comment = null;
            // previous token may not be a comment so we have to check if not null
            if (previous != null && previous.TokenID == DoNotIgnoreCommentsTokenWithChannels.COMMENT)
            {
                comment = previous?.Value;
            }
            return new DoNotIgnoreCommentIdentifier(token.Value, comment);
        }

    }

**Comment by b3b00** [comment]
@znakeeye I 've just push a prerelease nuget version 2.7.0-alpha . you can use it to test token channels if you want

**Comment by b3b00** [comment]
@znakeeye I have a working subparser feature on branch experiment/islands. 
here is my testcase.
I've still have some work for error reporting (build time and run time) and I will publish an alpha relase after that.

```c#
public enum DynamicLexer
    {
        EOF = 0,
        [Lexeme(GenericToken.Identifier,IdentifierType.AlphaNumeric)] ID = 1,
        
        [SubParser(typeof(SimpleExpressionParser),typeof(ExpressionToken),typeof(double),"SimpleExpressionParser_expressions")]
        [SingleLineIsland("``",channel:Channels.Islands)] MYISLANDSINGLE = 2,
        
        [SubParser(typeof(SimpleExpressionParser),typeof(ExpressionToken),typeof(double),"SimpleExpressionParser_expressions")]
        [MultiLineIsland("`","`",channel:Channels.Islands)] MYISLANDMULTI = 3
    }

    public class DynamicParser
    {
        [Production("main : id *")]
        public Ast Main(List<Ast> ids)
        {
            return new IdentifierList(ids);
        }

        [Production("id : ID")]
        public Ast SimpleId(Token<DynamicLexer> token)
        {
            // get previous token in channel 2 (COMMENT)
            var previous = token.Previous(Channels.Islands);
            double? island = null;
            // previous token may not be a comment so we have to check if not null
            if (previous != null && (previous.TokenID == DynamicLexer.MYISLANDMULTI ||
                                     previous.TokenID == DynamicLexer.MYISLANDSINGLE))
            {
                var result = (previous.ParsedValue as ParseResult<ExpressionToken, double>);
                island  = result.IsOk ? result?.Result : null;
            }

            return new AstCommentIdentifier(token.Value, island);
        }
    }

```

**Comment by znakeeye** [comment]
Sorry for late response. Did this feature make it into the master branch?

**Comment by b3b00** [comment]
hello @znakeeye , No I did not merge it to dev branch. I am still thinking of the real value of the feature compared to the added complexity.

you still can give it a try cloning my repo and using branch experiment/islands

I am quiet affraid by the documentation work needed to clearly explain channels and islands. these are not classic parsing concept but more antlr specifics.

i would greatly appreciate help for it if your still interested.
