### ISSUE TITLE
Special caret token?

### ISSUE THREAD

**Issue by znakeeye** [b3b00/csly#217]
I'd like to use `csly` for auto-completion, similar to what is described [here](https://tomassetti.me/autocompletion-editor-antlr/). Is it possible to define such a caret token using the current version?

**Comment by b3b00** [comment]
There is no such thing than CARET token.

But maybe you could try to parse the partial source code and see error report, looking for "unexpected token,.... expecting <here goes expected tokens>). I 've never tried it and I know there is some issues with error reporting with expression parsers (see #164 )

**Comment by znakeeye** [comment]
Interesting concept. Will try it out!
