### ISSUE TITLE
Evaluation of string to AST

### ISSUE THREAD

**Issue by brimfulofashar** [b3b00/csly#222]
Hi

It's not clear from the docs / wiki but when evaluating a string against the grammar, does CSLY provide an AST for traversal?

Thanks in advance.

**Comment by b3b00** [comment]
Hello @brimfulofashar , by definition a syntax parser only provides a CST. then it's up to you to build an AST visiting the CST.
A parser generator CAN NOT know the form and meaning of your AST and so build it.
This is true of any parser generator : CSLY or other like ANTLR, sprache....

I must agree that the general parsing principle must be better detailed in the wiki. I am working on it right now and will push it soon

**Comment by b3b00** [comment]
I slightly rewoked the wiki to better introduce parsing principle : https://github.com/b3b00/csly/wiki/Parsing-principle-and-BNF-Parser.
Does it look better to you ?

**Comment by b3b00** [comment]
@brimfulofashar , could you please answer ?! I need some feedback if you want to help me improve global CSLY quality

**Comment by brimfulofashar** [comment]
@b3b00 this is perfect. 

Thank you kindly
