### ISSUE TITLE
Generating an issue to start fixing documentation

### ISSUE THREAD

**Issue by aldosa** [b3b00/csly#246]
Documentation could use some TLC. Opening request to submit a branch. Fixes to orthography, spelling, navigation, etc. 

Thanks,

Aldo

**Comment by aldosa** [comment]
Unfortunately https://github.com/b3b00/csly.wiki.git/ appears read-only. Please provide access to edit or advise on how to branch. Would like to generate a pull request against it if possible.

**Comment by b3b00** [comment]
this should be done now. waiting for your PR

**Comment by b3b00** [comment]
For your PR, create a branch form master. I 've never use PR for github wikis so I don't how how  it works (does PR show like a classic PR or semthing different, you'll have to experiment)

**Comment by aldosa** [comment]
Thank you, Olivier, I’ll attempt a test push with some mods to the first page.  If it works and it’s acceptable I’ll continue with the rest.

**Comment by aldosa** [comment]
Thank you. Turns out I can edit directly on the web page. Made initial modifications to the home page. Will continue working on the other pages. Great project! I hope I can contribute code soon.

**Comment by aldosa** [comment]
Editing in progress. Great project! 

Thanks,

Aldo

**Comment by b3b00** [comment]
@aldosa I looked at your commits. Thanks you very much. Documentation is not the part I like the best with csly. Thanks to help make it better.
