### ISSUE TITLE
Lexer states like PLY?

### ISSUE THREAD

**Issue by TylerGubala** [b3b00/csly#265]
Hello,

I have a proprietary file structure that I am trying to parse.

There are sections to the file where one would expect only certain keywords.

In PLY, you can [create states](https://www.dabeaz.com/ply/ply.html#ply_nn20) to handle this sort of thing, that way a keyword in one section can be an identifier in another.

Is this possible with `sly`?

Thanks.

**Comment by b3b00** [comment]
Hello, 

Sadly there is no such thing like PLY lexer states. 
Would you mind give a minimal use case example so I can tell if possible to emulate this feature using native CSLY features.
Or even better enable this new feature directly in CSLY.

Thanks for reporting ways to enhance CSLY.

**Comment by b3b00** [comment]
@TylerGubala , i have started looking at implementing PLY's lexer states  in CSLY. Could you provide an example of your use case so I could check if it correctly address your issue ?

thanks
