### ISSUE TITLE
Feature request: add SourceLink support to NuGet package for debugging

### ISSUE THREAD

**Issue by LaXiS96** [b3b00/csly#308]
Hello,
first of all, thanks for this exceptional library!

It's common nowadays for NuGet packages to include symbols to allow seamless debugging into library source code, without having to replace package references etc.

I don't have any prior experience with NuGet packaging but something similar has been done for sprache/Sprache#174.
If anybody has experience with NuGets and is willing to implement this feature, please do so; otherwise I might try it myself and hope for the best.

Thank you

**Comment by b3b00** [comment]
Hello @LaXiS96,

great idea. Would you consider try it and submit a pull request ? I think that the sprache PR is a great starting point.

**Comment by b3b00** [comment]
Hello @LaXiS96 , I 've just published v2.9.0.6 nuget with symbols.
Could you try and tell me if sourcelink works ok for you ?

**Comment by b3b00** [comment]
@LaXiS96 nuget 2.9.0.6 was not ok. I've fixed it and 2.9.0.7 is ok (tested in visual studio pro 2019)
I have still some work to do to fix the github workflow that fails but still produces and publish a nuget.

I am closing the issue. 

Feel free to reopen if something is not ok on your side

**Comment by LaXiS96** [comment]
Hi,
debugging now seems to be working OK on VS 2022 Pro.

Thank you for your quick response!
