### ISSUE TITLE
Unexpected results for strings and doubles in expression parsing with generic lexer

### ISSUE THREAD

**Issue by LaXiS96** [b3b00/csly#311]
Hello,

I am getting unexpected results when using this configuration:
```csharp
enum TestTokens
{
    [String("'", "'")] STRING,
    [Double] DOUBLE,
    [Keyword("eq")] EQ,
}

class TestParser
{
    public static Parser<TestTokens, Expression> GetParser()
    {
        var builder = new ParserBuilder<TestTokens, Expression>();
        var result = builder.BuildParser(new TestParser(), ParserType.EBNF_LL_RECURSIVE_DESCENT, nameof(TestParser) + "_expressions");
        return result.Result;
    }

    [Operand]
    [Production("operand: STRING")]
    public Expression LiteralString(Token<TestTokens> value)
        => Expression.Constant(value.StringWithoutQuotes);

    [Operand]
    [Production("operand: DOUBLE")]
    public Expression LiteralDouble(Token<TestTokens> value)
        => Expression.Constant(value.DoubleValue);

    [Operation((int)TestTokens.EQ, Affix.InFix, Associativity.Left, 1)]
    public Expression BinaryOperator(Expression left, Token<TestTokens> operation, Expression right)
        => Expression.Equal(left, right);
}
```

The test and results:
```csharp
var parser = TestParser.GetParser();
var result1 = parser.Parse("123.456");
// result1.Result is a ConstantExpression with Value=123456D
// -> the decimal separator was ignored?

var result2 = parser.Parse("'str1' eq 'str2'");
// result2.Result is a ConstantExpression with Value="str1'eq 'tr2"
// -> it should have been a BinaryExpression with ConstantExpression arguments with values "str1" and "str2"
```

Thank you

**Comment by b3b00** [comment]
hello @LaXiS96 , i am missing the AST classes that inherit from expression to fully reproduce your issue. could you share them ?

**Comment by LaXiS96** [comment]
The sample code is only using LINQ expressions so a `using System.Linq.Expressions;` should be sufficient; I don't have other custom classes.

**Comment by b3b00** [comment]
For the first case "123.465" i do not reproduce the problem. the value is 123.456d
For the second there is a real issue. the string lexing is buggy. I need to investigate further.

Thanks for reporting

**Comment by LaXiS96** [comment]
Thank you.

For the double issue the problem is in the culture used in `Token<T>.DoubleValue` ([lexer/Token.cs#L219](https://github.com/b3b00/csly/blob/dev/sly/lexer/Token.cs#L219)), in my case `CultureInfo.CurrentCulture` is `it-IT` which explains why the dot is ignored since it is a thousands separator in that culture.
On the other hand, `parser.Parse("123.45")` fails the TryParse on line 219 and gets parsed correctly by line 222.

I believe, for the purposes of expression parsing, that the invariant culture should always be used instead of any local culture.
Additionally, in the `it-IT` culture the decimal separator is a comma so the logic behind `GenericToken.Double` wouldn't work anyway.

**Comment by b3b00** [comment]
This is make me think that the double lexeme should be configurable to be able to choose the decimal separator.
Something like 
```csharp
[Double(",")]
DOUBLE_WITH_COMA_AS_DECIMAL_SEPARATOR

[Double(".")]
DOUBLE_WITH_DOT_AS_DECIMAL_SEPARATOR
``` 

then the Token<T>.DoubleValue could use the separator to compute the double value (independtly of any culture).
This will be for later. For now I concentrate on the other issue concerning the string token.

**Comment by b3b00** [comment]
Sorry @LaXiS96 i've closed the issue too quickly. 
The fix for the string issue is ready. I am now working on the double token issue. I will publish a new version soon with the 2 fixes

**Comment by b3b00** [comment]
version 2.9.0.8 is publisheed and solved the string part of the issue.
custom decimal delimiter for doubles is a bit more tricky than i thought and will come later

Thanks for your help

**Comment by b3b00** [comment]
version 2.9.0.9 fixes the double issue, using a configurable decimal separator on the double lexeme : 

```c#

// comma decimal separator
[Double(",")]
DOUBLE_WITH_COMA_AS_DECIMAL_SEPARATOR

// dot decimal separator
[Double(".")]
DOUBLE_WITH_DOT_AS_DECIMAL_SEPARATOR

```

**Comment by LaXiS96** [comment]
Thank you very much for both fixes, I can confirm it's now working as expected!

**Comment by b3b00** [comment]
Thanks for return and confirmation, it helps so much
