### ISSUE TITLE
[Question] Why/Should all visitor function return the same type

### ISSUE THREAD

**Issue by remygrandin** [b3b00/csly#314]
Hi,

I'm trying to design a lexer/parser to handle an expression like "myproperty -eq 10" (at first)

However, I'm facing an error where I'm not sure if I miss something in the concept of how I should do it the "proper" way

```
internal enum ExpressionToken
    {
        [Lexeme("\\(")]
        LParen = 1,

        [Lexeme("\\)")]
        RParen = 2,

        [Lexeme("[ \\t]+", isSkippable: true)]
        WhiteSpace = 3,

        [Lexeme("[a-zA-Z\\.]+")]
        Property = 4,

        [Lexeme(@"""[^""]+""")]
        String = 5,

        [Lexeme("[0-9]+[\\.,][0-9]+")]
        Number = 6,

        [Lexeme("[0-9]+")]
        Int = 7,

        [Lexeme("-eq(ual)?")]
        Op_Equal = 101,

        [Lexeme("-(lt|lowerthan)")]
        Op_LowerThan = 102,
    }

internal class ExpressionParser
    {
        [Production("primary: Int")]
        public Int32 Primary_Int(Token<ExpressionToken> intToken)
        {
            return intToken.IntValue;
        }

        [Production("primary: Number")]
        public Double Primary_Number(Token<ExpressionToken> numberToken)
        {
            return numberToken.DoubleValue;
        }

        [Production("primary: String")]
        public string Primary_String(Token<ExpressionToken> stringToken)
        {
            return stringToken.Value;
        }

        [Production("op: Op_Equal")]
        [Production("op: Op_LowerThan")]
        public string Op(Token<ExpressionToken> stringToken)
        {
            return stringToken.Value.Skip(1).ToString();
        }

        [Production("compare: Property op primary")]
        public Clause Compare(Token<ExpressionToken> property, string op, object primary)
        {
            return new Clause()
            {
                Property = property.Value,
                Op = op as string,
                Value = primary,
            };
        }
    }
```

```
    var parserInstance = new ExpressionParser();
    var builder = new ParserBuilder<ExpressionToken, Clause>();
    var interm = builder.BuildParser(parserInstance, ParserType.LL_RECURSIVE_DESCENT, "compare");
    var Parser = interm.Result;

    var res = Parser.Parse("abcd -eq 12");
```

The parser failed to be build with PARSER_INCORRECT_VISITOR_RETURN_TYPE and PARSER_INCORRECT_VISITOR_PARAMETER_TYPE errors

I understand I can circunvent this issue by creating a root value wrapper and create sub types so all visitor function would be legally the same type, but it seem a pain to wrap when most of my terminator will be standard value types (string, int, ...)

Why should all visitor functions return the type specified on the parserbuilder ?
And is there a better way to define this kind of parser ?

**Comment by b3b00** [comment]
You have to understand that the return of a visitor method may be use by another visitor as a parameter. If you do not enforce strict typing rules you will face cast error at runtime. So this rule is simply there as a safety rule. Furthermore I think that a parser output should always be an asbtract syntax tree (AST) . An AST is merely a tree implementing the [composite pattern](https://en.wikipedia.org/wiki/Composite_pattern). In a composite pattern all nodes and leaves implement the same root interface.

So as you guess you have to implement a wrapper around int ,double and string values. This wrapper should inherit from a root interface (let 's call it IExpression). And your Clause class should also inherit from IExpression.

This may seem weird but in fact all this items are expressions  : 
- either a scalar value (int ,double or string)
- or a comparison expression

you can find further typing safety considerations in the wiki : [typing rules](https://github.com/b3b00/csly/wiki/defining-your-parser#typing-rules)

Except the "every visitor method should return the same type" rule, your parser looks perfect.

Hope this explanation is clear enough. let me know

**Comment by remygrandin** [comment]
Thanks for the detailed explaination.

I figured out as much, I had succeded with a bone headed wrapper like this :

```
public class ValueWrapper
    {
        public Type ValueType { get; set; }

        public object Value { get; set; }

        public ValueWrapper(Type type, object value)
        {
            ValueType = type;
            Value = value;
        }
    }
```

It worked but was not "clean". I will try to do a proper AST with inheritance and such :-)

Thanks for you library and all your time on it ^^
