### ISSUE TITLE
Any way to timeout the parser when it takes too long ?

### ISSUE THREAD

**Issue by leryss** [b3b00/csly#323]
Hi, is there any way to timeout the parsing process if it takes too long ?

**Comment by b3b00** [comment]
hello @leryss,  there is no builtin timeout management in csly. you ll have to manage it on your own. see https://stackoverflow.com/questions/13513650/how-to-set-timeout-for-a-line-of-c-sharp-code for example. 

But it' s strange that you'd need it. Maybe something is wrong with your parser. Share it and i will be glad to look at it if you want.

Olivier

**Comment by b3b00** [comment]
hello @leryss,  there is no builtin timeout management in csly. you ll have to manage it on your own. see https://stackoverflow.com/questions/13513650/how-to-set-timeout-for-a-line-of-c-sharp-code for example. 

But it' s strange that you'd need it. Maybe something is wrong with your parser. Share it and i will be glad to look at it if you want.

Olivier

**Comment by b3b00** [comment]
@leryss , are you ok with my answer. I wait a bit before closing the issue
