### ISSUE TITLE
What's the order of priority for Generic Tokens?

### ISSUE THREAD

**Issue by TamaBaka** [b3b00/csly#328]
I'm having trouble getting the string to tokenize properly because certain rules take precedence over others resulting in misclassification.

Is it the Generic Token Type and then the enum value?  Or is it the highest enum value that gets tokenized first?

    

 ```
public enum StdToken
    {

        [Keyword("XL")]
        [Push("xlmode")]
        START_X = 100,        

        [Sugar("@")]
        [Push("dmode")]
        START_D = 101,
  
        [Lexeme(GenericToken.UpTo, ">>", "\0")]
        [Mode("dmode", "xlmode")]
        [Pop]
        OPS = 103,

        [Sugar(">>")]
        INSTALL = 15,

        [Sugar("(")]
        LPAREN = 40,

        [Sugar(")")]
        RPAREN = 41,

        [Keyword("Int")]
        [Keyword("String")]
        [Keyword("Optset")]
        [Keyword("Money")]
        [Keyword("Decimal")]
        [Keyword("EtnRef")]
        CONVERT = 104,

        [Sugar(":")]
        COLON = 105,
    }

```

Given the following:
"XL(Key Metrics/C455) >> String: @working_adj.amount",

It's coming out as 
START_X OPS INSTALL CONVERT OPS  - the last OPS tokenized as "**: @working_adj.amount**"

when it should be:
START_X OPS INSTALL CONVERT COLON START_D OPS

**Comment by b3b00** [comment]
Hello @TamaBaka,
ther is no priority rule. I am looking at it right now.

**Comment by TamaBaka** [comment]
As a sidenote, it was working fine for: "XL(Key Metrics/C455) >> String: @working_adj.amount"

START_X OPS INSTALL START_D OPS

Then I decided that it needed explicit casting in case I get a non-string type from XL(), so I added the CONVERT and COLON tokens and I've been playing around with enum constants since since the tokenization results change as I make certain tokens higher or lower than the others.

**Comment by b3b00** [comment]
I think I have identified the problem. It's a bug in the lexer modes management. As you declared that the keyword XL push to xlmode, the generic lexer think that every keyword needs to push the xlmode, messing the lexer fater the String keyword. this is fixable, i will take care of it real quickly. thanks for reporting.
I have a fix that produces the expected result.
Now I will check if there is no regression and if ok publish a new version soon

**Comment by b3b00** [comment]
@TamaBaka version 2.9.3.0 is now published. It solves your issue. Could you try and tell me if it's ok for you ?

**Comment by TamaBaka** [comment]
Confirmed.  That change gives me the tokens that I want now.  Thank you again!

**Comment by b3b00** [comment]
thanks again for reporting @TamaBaka. I guess you are the first csly user to try the lexer modes feature using keywords are mode triggers.

**Comment by TamaBaka** [comment]
Unless I misunderstand how it works, I think that csly's mode system is a bit different from Antlr's.  At the very least, I didn't have to separate the grammar from the lexer and that makes it intuitive since I can seamlessly insert modes into my grammar without having to rewrite my code.

I needed to break my expression up into subclauses so I can perform unique actions on each subclause.  But I was forced to give up on Antlr's mode system because their tutorials emphasized the unified grammar.  There was almost no documentation on the modes system itself and the last thing on people's minds is how to set up separate Lexer and Grammar files for new users.

Anyway, I think that newer developers would shy away from the modes feature if they were expecting it to have that kind of difficulty.

As for using keywords for mode triggers, I have no formal training in Lexers and I hadn't realized that keywords weren't used in the list of examples.  It worked, somewhat, when I tried it.  But the fact that it was unintended would explain why it needed so much tuning.

**Comment by b3b00** [comment]
When working on lexer modes I was targetin languages like XML or templating languages that use sugar token as mode delimiter. So I did not test keywords as mode delimiter , I shoud have...
I am not sure to have fully understood your last message. Finally are you finding CSLY lexer modes better suited to your use case than Antlr's one ?

**Comment by TamaBaka** [comment]
It's not better suited since I think they both are used for the same purpose.  But I think it's far easier in csly since you add them in place.  

With Antlr, you're basically treated as an advanced user.  New users get to use the combined grammar (grammar Speak;), but modes will not compile until you separate the grammar (lexer grammar Speak), create a parser, then customize and include both.  But there're barely any tutorials on the web for handling the two separately so I think you need to go out and purchase one of those thick "phone" books to figure out how to do it...
