### ISSUE TITLE
Very long execution time and large memory consumption

### ISSUE THREAD

**Issue by gilroitto** [b3b00/csly#414]
I'm trying to write a simple programming language with csly but am running into performance issues.

Here is the parser (currently it does nothing other than reproducing the expression string):

`
    public enum TestingLex
    {
        #region keywords 0 -> 19

        [Lexeme(GenericToken.KeyWord, "IF")]
        [Lexeme(GenericToken.KeyWord, "if")]
        IF = 1,

        [Lexeme(GenericToken.KeyWord, "THEN")]
        [Lexeme(GenericToken.KeyWord, "then")]
        THEN = 2,

        [Lexeme(GenericToken.KeyWord, "ELSE")]
        [Lexeme(GenericToken.KeyWord, "else")]
        ELSE = 3,

        [Lexeme(GenericToken.KeyWord, "WHILE")]
        [Lexeme(GenericToken.KeyWord, "while")]
        WHILE = 4,

        [Lexeme(GenericToken.KeyWord, "DO")]
        [Lexeme(GenericToken.KeyWord, "do")]
        DO = 5,

        [Lexeme(GenericToken.KeyWord, "SKIP")]
        [Lexeme(GenericToken.KeyWord, "skip")]
        SKIP = 6,

        [Lexeme(GenericToken.KeyWord, "TRUE")]
        [Lexeme(GenericToken.KeyWord, "true")]
        TRUE = 7,

        [Lexeme(GenericToken.KeyWord, "FALSE")]
        [Lexeme(GenericToken.KeyWord, "false")]
        FALSE = 8,

        [Lexeme(GenericToken.KeyWord, "NOT")]
        [Lexeme(GenericToken.KeyWord, "not")]
        NOT = 9,

        [Lexeme(GenericToken.KeyWord, "AND")]
        [Lexeme(GenericToken.KeyWord, "and")]
        AND = 10,

        [Lexeme(GenericToken.KeyWord, "OR")]
        [Lexeme(GenericToken.KeyWord, "or")]
        OR = 11,

        [Lexeme(GenericToken.KeyWord, "PRINT")]
        [Lexeme(GenericToken.KeyWord, "print")]
        PRINT = 12,

        //[Lexeme(GenericToken.KeyWord, "BEGIN")]
        //[Lexeme(GenericToken.KeyWord, "begin")]
        //BEGIN = 13,

        //[Lexeme(GenericToken.KeyWord, "END")]
        //[Lexeme(GenericToken.KeyWord, "end")]
        //END = 14,

        #endregion

        #region literals 20 -> 29

        [Lexeme(GenericToken.Identifier)]
        IDENTIFIER = 20,

        [Lexeme(GenericToken.String)]
        STRING = 21,

        [Lexeme(GenericToken.Int)]
        INT = 22,

        [Lexeme(GenericToken.Double)]
        DOUBLE = 23,

        #endregion

        #region operators 30 -> 49

        [Lexeme(GenericToken.SugarToken, ">")]
        GREATER = 30,

        [Lexeme(GenericToken.SugarToken, "<")]
        LESSER = 31,

        [Lexeme(GenericToken.SugarToken, "==")]
        EQUALS = 32,

        [Lexeme(GenericToken.SugarToken, "!=")]
        DIFFERENT = 33,

        [Lexeme(GenericToken.SugarToken, ".")]
        DOT = 34,

        [Lexeme(GenericToken.SugarToken, ":=")]
        ASSIGN = 35,

        [Lexeme(GenericToken.SugarToken, "+")]
        PLUS = 36,

        [Lexeme(GenericToken.SugarToken, "-")]
        MINUS = 37,

        [Lexeme(GenericToken.SugarToken, "*")]
        TIMES = 38,

        [Lexeme(GenericToken.SugarToken, "/")]
        DIVIDE = 39,

        #endregion

        #region sugar 50 ->

        [Lexeme(GenericToken.SugarToken, "(")]
        LPAREN = 50,

        [Lexeme(GenericToken.SugarToken, ")")]
        RPAREN = 51,

        [Lexeme(GenericToken.SugarToken, "{")]
        LCURLYBRACE = 52,

        [Lexeme(GenericToken.SugarToken, "}")]
        RCURLYBRACE = 53,

        [Lexeme(GenericToken.SugarToken, "[")]
        LBRACKET = 54,

        [Lexeme(GenericToken.SugarToken, "]")]
        RBRACKET = 55,

        [Lexeme(GenericToken.SugarToken, ";")]
        SEMICOLON = 56,

        [Lexeme(GenericToken.SugarToken, ",")]
        COMMA = 57,

        EOF = 0

        #endregion
    }

    public class TestingParser
    {

        #region boolean
        [Production("boolean: TRUE")]
        public string BooleanTrue(Token<TestingLex> trueToken)
        {
            return "true";
        }
        [Production("boolean: FALSE")]
        public string BooleanFalse(Token<TestingLex> falseToken)
        {
            return "false";
        }
        #endregion

        #region variable

        [Production("variable: IDENTIFIER")]
        public string VariableIdentifier(Token<TestingLex> idToken)
        {
            var varName = idToken.StringWithoutQuotes;
            return varName;
        }
        #endregion

        #region group
        [Production("group: LPAREN expression RPAREN")]
        public string Group(Token<TestingLex> lparen, string expression, Token<TestingLex> rparen)
        {
            return "(" + expression + ")";
        }

        #endregion

        #region primary
        [Production("primary: boolean")]
        public string PrimaryBoolean(string boolean)
        {
            return boolean;
        }

        [Production("primary: INT")]
        public string PrimaryInt(Token<TestingLex> intToken)
        {
            return intToken.IntValue.ToString();
        }
        [Production("primary: DOUBLE")]
        public string PrimaryDouble(Token<TestingLex> doubleToken)
        {
            return doubleToken.DoubleValue.ToString();
        }

        [Production("primary: variable")]
        public string PrimaryIdentifier(string variable)
        {
            return variable;
        }

        [Production("primary: STRING")]
        public string PrimaryString(Token<TestingLex> strToken)
        {
            var str = strToken.StringWithoutQuotes;
            return str;
        }

        [Production("primary: group")]
        public string PrimaryGroup(string group)
        {
            return group;
        }

        [Production("primary : functioncall")]
        public string PrimaryFunctioncall(string functioncall)
        {
            return functioncall;
        }

        #endregion

        #region begin end

        [Production("begin_end : LCURLYBRACE block RCURLYBRACE")]
        public string BeginEnd(Token<TestingLex> lcurlybraceToken, string block, Token<TestingLex> rcurlybraceToken)
        {
            return "{" + "\r\n" + block + "\r\n" + "}";
        }

        #endregion

        #region block
        [Production("block : statement")]
        public string Block(string statement)
        {
            return statement;
        }

        [Production("block : statement block")]
        public string Block(string statement, string blockExpression)
        {
            return statement + "\r\n" + blockExpression;
        }

        #endregion

        #region statement
        [Production("statement : expression SEMICOLON")]
        public string Statementstring(string expression, Token<TestingLex> semicolonToken)
        {
            return expression + ";";
        }

        // A := ...
        [Production("statement : assign SEMICOLON")]
        public string StatementAssign(string assign, Token<TestingLex> semicolonToken)
        {
            return assign + ";";
        }

        //// begin ... end
        [Production("statement : begin_end")]
        public string StatementBeginEnd(string beginend)
        {
            return beginend;
        }

        #endregion

        #region assign
        // A := ...
        [Production("assign : variable ASSIGN expression")]
        public string AssignExpression(string variable, Token<TestingLex> assignToken, string right)
        {
            return variable + ":=" + right;
        }
        #endregion

        #region expression
        //expression ->
        //  logiclevel (AND, OR) ->
        //    comparelevel (<, >, !=, ==) ->
        //      sumlevel (+, -) ->
        //        factorlevel (*, ) ->
        //          primary

        [Production("expression : logiclevel AND expression")]
        [Production("expression : logiclevel OR expression")]
        public string LogicExpression(string left, Token<TestingLex> operatorToken, string right)
        {
            return left + operatorToken.Value + right;
        }

        [Production("expression : logiclevel")]
        public string LogicExpression(string comparelevel)
        {
            return comparelevel;
        }

        [Production("logiclevel : comparelevel GREATER logiclevel")]
        [Production("logiclevel : comparelevel LESSER logiclevel")]
        [Production("logiclevel : comparelevel EQUALS logiclevel")]
        [Production("logiclevel : comparelevel DIFFERENT logiclevel")]
        public string CompareExpression(string left, Token<TestingLex> operatorToken, string right)
        {
            return left + operatorToken.Value + right;
        }

        [Production("logiclevel : comparelevel")]
        public string CompareExpression(string comparelevel)
        {
            return comparelevel;
        }

        [Production("comparelevel : sumlevel PLUS comparelevel")]
        public string PlusExpression(string left, Token<TestingLex> operatorToken, string right)
        {
            return left + "+" + right;
        }
        [Production("comparelevel : sumlevel MINUS comparelevel")]
        public string MinusExpression(string left, Token<TestingLex> operatorToken, string right)
        {
            return left + "-" + right;
        }

        [Production("comparelevel : sumlevel")]
        public string CalcExpression(string sumlevel)
        {
            return sumlevel;
        }
        #endregion

        #region sumlevel (term)
        [Production("sumlevel : factorlevel TIMES sumlevel")]
        public string Times(string left, Token<TestingLex> operatorToken, string right)
        {
            return left + "*" + right;
        }
        [Production("sumlevel : factorlevel DIVIDE sumlevel")]
        public string Divide(string left, Token<TestingLex> operatorToken, string right)
        {
            return left + "/" + right;
        }

        [Production("sumlevel : factorlevel")]
        public string Sumlevel_Factor(string factorValue)
        {
            return factorValue;
        }
        #endregion

        #region factor
        [Production("factorlevel : primary")]
        public string PrimaryFactor(string primValue)
        {
            return primValue;
        }

        [Production("factorlevel : MINUS factorlevel")]
        public string Factor(Token<TestingLex> minus, string factorValue)
        {
            return "-" + factorValue;
        }
        #endregion

        #region functioncall
        // function : variable ( parameters )
        // function : variable ( )
        [Production("functioncall : variable LPAREN callparameters RPAREN")]
        public string Functioncall(string variableExpression, Token<TestingLex> lparen, string parameters, Token<TestingLex> rparen)
        {
            return variableExpression + "(" + parameters + ")";
        }

        [Production("functioncall : variable LPAREN RPAREN")]
        public string Functioncall(string variableExpression, Token<TestingLex> lparen, Token<TestingLex> rparen)
        {
            return variableExpression + "()";
        }

        [Production("callparameters : expression COMMA callparameters")]
        public string Function(string paramExpression, Token<TestingLex> comma, string parameters)
        {
            return paramExpression + ", " + parameters;
        }

        [Production("callparameters : expression")]
        public string Function(string paramExpression)
        {
            return paramExpression;
        }
        #endregion
    }
`

Here is how I create the parser:
`
        public static Parser<TestingLex, string> TestingParser()
        {
            var parserInstance = new TestingParser();
            var builder = new ParserBuilder<TestingLex, string>();
            var buildResult = builder.BuildParser(parserInstance, ParserType.EBNF_LL_RECURSIVE_DESCENT, "block");//line-based, 1 statement per line.
            if (buildResult.IsError)
                throw new Exception(string.Join("|", buildResult.Errors.Select(e => e.ToString())));
            var parser = buildResult.Result;

            return parser;
        }
`

Here is a test that takes > 2 minutes to execute and several GB in memory is used for parsing this expression )but it completes):

`
string code = "funcA(funcC(B==2));";
var parser = ParserService.TestingParser();

var pResult = parser.Parse(code);
if (pResult.IsError)
{
     Console.WriteLine("=== ERROR ===");
     pResult.Errors.ForEach(error => Console.WriteLine(error.ErrorMessage));
}
else
{
    var result = pResult.Result;
    Console.WriteLine($"result is {result}");
}
`
If I reduce the expression to:
`funcA(funcB());`

the execution time is reduced to under 1 minut, but still it is quite expensive to parse this simple expression.

Maybe my expressions are written poorly?

**Comment by b3b00** [comment]
Hello @gilroitto , looking at your parser I cant see any obvious error.
Thanks for sharing it, I will look at it tomorrow morning.
Have you looked at the expression parsing facility of CSLY : https://github.com/b3b00/csly/wiki/expression parsing
It could help

**Comment by b3b00** [comment]
Hello @gilroitto , looking at your parser I cant see any obvious error.
Thanks for sharing it, I will look AT it tomorrow morning.
Have you looked at the expression parsing facility of CSLY : https://github.com/b3b00/csly/wiki/expression parsing
It could help

Could you also provide the output of `dotnet --info`, please ?

**Comment by gilroitto** [comment]
Thank you @b3b00 ! I'm getting started with your library, will look into your expression parsing link, 

The project is running on .NET 7.0

Here is the output of dotnet --info
```
.NET SDK:
 Version:   7.0.102
 Commit:    4bbdd14480

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19045
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.102\

Host:
  Version:      7.0.14
  Architecture: x64
  Commit:       808851b07a

.NET SDKs installed:
  3.1.426 [C:\Program Files\dotnet\sdk]
  5.0.403 [C:\Program Files\dotnet\sdk]
  5.0.404 [C:\Program Files\dotnet\sdk]
  7.0.102 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.21 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.25 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.21 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.25 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found
```

**Comment by b3b00** [comment]
@gilroitto, I suspect some kind of excessive backtracking. Using the expression parsing CSLy feature should help. 
I've modified your parser to use it and will test.
If result is positive, I am thinking about a way to generalize the optimization in place for expression parsin, and hoppefully we could have better performance with your parser let untouched.

**Comment by b3b00** [comment]
@gilroitto indeed using the expression parsing get things real better. in fact it's almost immediate.
You can check how I've modified it on branch [fix/issue414](https://github.com/b3b00/csly/tree/fix/issue414). Beware, that this modification may not fit your exact needs so keep time to review it. 

I will now try to make it available for any kind of grammar as it may exist some case where using expresssion parsin is not an option.

Thanks for reporting

**Comment by b3b00** [comment]
So far, i've get time down to 10 seconds for parsing `funcA(funcC(B==2));`.
That's still too long but it gets way better and I keep on to make it on par with the expression parsing which is below 200 ms

**Comment by b3b00** [comment]
@gilroitto, after searching many way I've found that I can get similar performance slightly modifying your grammar: 
```csharp
[Production("logiclevel : comparelevel GREATER logiclevel")]
[Production("logiclevel : comparelevel LESSER logiclevel")]
[Production("logiclevel : comparelevel EQUALS logiclevel")]
[Production("logiclevel : comparelevel DIFFERENT logiclevel")]
public string CompareExpression(string left, Token<TestingLex> operatorToken, string right)
{
    return left + operatorToken.Value + right;
}
```

becomes : 

```csharp
[Production("logiclevel : comparelevel [GREATER|LESSER|EQUALS|DIFFERENT] logiclevel")]
public string CompareExpression(string left, Token<Issue414Token> operatorToken, string right)
{
    return left + operatorToken.Value + right;
}
``` 

As you see i use an [alternate construct](https://github.com/b3b00/csly/wiki/EBNF-parser#alternate-choice) that lists all possible operator for a same level (I've made the same modification for the other levels)
This avoid backtracking which is the main cause of slowliness.

For now I am stopping research to solve this systematically. If you agree with the move to [expression parsing](https://github.com/b3b00/csly/wiki/expression) I close the issue

**Comment by gilroitto** [comment]
Thank you for this suggestion, I will modify. Also I see you've made changes to the code base which I assume are the performance improvements you've made. I am super happy you addressed this so quickly. Yes of course close this issue. I will update the library as soon as it released and test it out. I will report back again if there are still performance issues. I plan to create quite a big language.

**Comment by b3b00** [comment]
@gilroitto a new version is published and available on nuget.org : [CSLY 2.9.8](https://www.nuget.org/packages/sly/2.9.8)

**Comment by gilroitto** [comment]
Awesome. I've updated the nuget package and here are the results I got now. 

With the original Parser rules as in the original post.
funcA(funcC(B==2));
Parsing: 21 s, 5 GB memory used

With the improved grammar - https://github.com/b3b00/csly/blob/dev/tests/ParserTests/Issue414/Issue414AltParser.cs
funcA(funcC(B==2));
Parsing 100 ms, limited memory usage.
