### ISSUE TITLE
Empty data causes "Unexpected end of stream" error?

### ISSUE THREAD

**Issue by znakeeye** [b3b00/csly#443]
Am I doing something wrong? Parsing an empty string causes "Unexpected end of stream" error.

**Sample app** below. How can I get a successful parse result for an empty string, i.e. `EOF`?

```c#
using sly.lexer;
using sly.parser.generator;

namespace ConsoleApp1;

public interface INode
{
}

public class TemplateNode : INode
{
    public TemplateNode(List<INode> items)
    {
    }
}

[Lexer(IgnoreEOL = false)]
public enum TemplateLexer
{
    EOF = 0,

    [Sugar("\r\n", 28, IsLineEnding = true)]
    [Mode]
    CRLF,
    [Sugar("\n", 28, IsLineEnding = true)]
    [Mode]
    LF
}

public class TemplateParser
{
    [Production("template: eol*")]
    public INode Template(List<INode> items)
    {
        return new TemplateNode(items);
    }

    [Production("eol : [CRLF | LF]")]
    public INode EndOfLine(Token<TemplateLexer> eol) => throw new NotImplementedException();
}

internal class Program
{
    static void Main(string[] args)
    {
        var templateParser = new TemplateParser();
        var builder = new ParserBuilder<TemplateLexer, INode>();

        var parser = builder.BuildParser(templateParser, ParserType.EBNF_LL_RECURSIVE_DESCENT, "template");

        var result = parser.Result.Parse("");

        Console.WriteLine($"Result OK? {result.IsOk}");
        
        Console.WriteLine("Errors:");
        result.Errors.ForEach(Console.WriteLine);
    }
}
```

**Comment by b3b00** [comment]
@znakeeye , I dont usally use eol sensitive grammars so I may have missed this one, thanks for reporting. I will look at it quickly.

**Comment by b3b00** [comment]
@znakeeye which csly version are you using ? Your issue may be causes by #441 fix so 3.1.1 may cause  not work with your grammars ? Will test it

**Comment by znakeeye** [comment]
The latest version, `3.1.1`.

**Comment by b3b00** [comment]
Hello @znakeeye,

There is an issue with your lexer definition.
You defined `LF` and `CRLF` lexeme on channel 28. But CSLy parser only use lexeme defined on channel "default" ( channel 0). So  despite being lexed LF and CRLF are ignored at the parse step leading to an End Of Stream error.
So correct lexer configuration is : 
```c# 
[Lexer(IgnoreEOL = false)]
public enum Issue443Lexer
{
    EOF = 0,
   // note : no channel definition here so CRLF is sent to default channel 
    [Sugar("\r\n", IsLineEnding = true)]
    [Mode]
    CRLF,
   // note : no channel definition here so LF is sent to default channel
    [Sugar("\n",  IsLineEnding = true)]
    [Mode]
    LF
}
```

Nevertheless there is stille  an issue with you test case  when parsing an empty string: 
``` c# 
 var result = parser.Result.Parse("");
``` 
Parser should succeed as we expect 0 or more CRLF or LF.  I keep on looking on this.

But now with the channel fix we succeed at parsing a string with a newline 
``` c# 
 var result = parser.Result.Parse(@"
");
```

**Comment by b3b00** [comment]
@znakeeye , I 've fixed the last problem. a new nuget 3.1.2 version is available.
tell me if you find any other issue
