### ISSUE TITLE
Confusing mode results

### ISSUE THREAD

**Issue by TamaBaka** [b3b00/csly#487]
I'm getting some weird results from this line:
@g_capcalc >> EtnRef: @appcapcalc.bankcapconfigid

```
START_D [@] @line 0, column 0 on channel 0
OPS [g_capcalc ] @line 0, column 1 on channel 0
INSTALL [>>] @line 0, column 11 on channel 0
CONVERT [EtnRef] @line 0, column 14 on channel 0
OPS [: @appcapcalc.bankcapconfigid] @line 0, column 20 on channel 0
<<EOS>>
```

I wanted to get something like this instead:
```
START_D [@]
OPS [g_capcalc]
INSTALL [>>]
CONVERT [EtnRef]
COLON [:]
START_D [@]
OPS [appcapcalc.bankcapconfigid]
```

After stepping through the lines, I think my issue is caused by modes being misclassified.  It should be:
default -> dmode -> default -> convert -> default -> dmode

Instead, I'm getting 
default -> calcmode -> default -> xlmode

Once in xlmode or any other mode, I can't and shouldn't start a different mode based on my current design.

As a sidenote, I notice that the modes pushed follow the order that they're defined in the source code...but maybe I'm just setting the tokens up wrong to begin with.

```
public enum StdToken
{

    [Keyword("CC")]
    [Push("calcmode")]
    [Mode("default")]
    START_C = 102,

    [Keyword("XL")]
    [Push("xlmode")]
    [Mode("default")]
    START_X = 100,          

    [Sugar("@")]
    [Push("dmode")]
    [Mode("default")]
    START_D = 101,

    [Sugar("$")]
    [Push("lvar")]
    [Mode("default")]
    VARSTART = 60,

    [Lexeme(GenericToken.UpTo, ">>", "??")]
    [Mode("xlmode", "dmode", "calcmode", "lvar")]
    [Pop]
    OPS = 103,

    [Sugar(">>")]
    [Mode("default")]
    INSTALL = 15,

    [Sugar("??")]
    [Mode("default")]
    IFNULLTHEN = 49,

    [Sugar("{")]
    [Mode("default")]
    BLOCK_START = 50,

    [Sugar("}")]
    [Mode("default")]
    BLOCK_END = 48,

    [Sugar("(")]
    [Mode("default")]
    LPAREN = 40,

    [Sugar(")")]
    [Mode("default")]
    RPAREN = 41,

    [Sugar(":")]
    [Mode("convert")]
    [Pop]
    COLON = 43,

    [Sugar("?")]
    [Mode("convert")]
    ISNULLABLE = 105,

    [Keyword("Int")]
    [Keyword("String")]
    [Keyword("Optset")]
    [Keyword("Money")]
    [Keyword("Decimal")]
    [Keyword("EtnRef")]
    [Push("convert")]
    CONVERT = 62,

    [Lexeme(GenericToken.String, "\"", "\\")]
    CONST_BLOCK = 31,


    [AlphaId]
    LOCALVAR = 61,

    EOF = 0

    //[String]
    //STRING = 4
}
```

As another sidennote, I figured out what mode that I'm using by setting a breakpoint on line 312 in GenericLexer.cs

```
	private FSMLexer<GenericToken> SetLexerMode(FSMMatch<GenericToken> r, Stack<FSMLexer<GenericToken>> lexersStack)
	{
		FSMLexer<GenericToken> fSMLexer = lexersStack.Peek();
		if (!r.IsEOS)
		{
			if (r.IsPop)
			{
				lexersStack.Pop();
				fSMLexer = lexersStack.Peek();
				r.NewPosition.Mode = fSMLexer.Mode;
				return fSMLexer;
			}
			if (r.IsPush)
			{
BP>				fSMLexer = SubLexersFsm[r.NewPosition.Mode];
				lexersStack.Push(fSMLexer);
			}
			else
			{
				fSMLexer = SubLexersFsm[r.NewPosition.Mode];
			}
		}
		return fSMLexer;
	}
```

[Source.zip](https://github.com/user-attachments/files/17351253/Source.zip)

**Comment by b3b00** [comment]
Hello @TamaBaka , thanks for reporting. Modes are reporting, modes are surely not the most used feature and may still have issues. I will look at it quickly.

Thanks for adding a test case it will greatly help debugging 👍

**Comment by TamaBaka** [comment]
If it requires a massive reworking, I did find a workaround so you don't have to prioritize this ticket.  Basically, I would just condense all of the modes down to two, default and altmode.  With the absence of choice, the tokenizer pushes the proper mode onto the stack at that point.

Multiple modes would be useful for future expansions of my custom language, but I don't need it now.  Right now it's really just being used to make my code clearer.  Explicitly define which commands apply to which group of actions.

**Comment by b3b00** [comment]
This looks the same as #328 that you've already reported. I will look at it tomorrow morning.

**Comment by b3b00** [comment]
Indeed I think that multiple mode (specifically those delimited by keywords) are not correctly managed. it surely relates to your issue #328.
I will  look at it as it's a real bug.

**Comment by b3b00** [comment]
@TamaBaka , i've fixed it. it was indeed linked to #328. I didnt manage the case when many keywords can change modes (push or pop).  PR is in progress. as soon as it is ok, I will publish a new nuget version

**Comment by b3b00** [comment]
@TamaBaka , CSLY v3.3.2 is published. Could you try and tell if all is ok for your use case please ? And close issue if you re ok

**Comment by b3b00** [comment]
a new version 3.5.3 is building to fix an issue with `[Pop]` tokens that i've just discovered

**Comment by TamaBaka** [comment]
I tried testing it.  When I used the test code above:
@g_capcalc >> EtnRef: @appcapcalc.bankcapconfigid

```
@(g_capcalc) >> EtnRef: @(appcapcalc.bankcapconfigid)
START_D [@] @line 0, column 0 on channel 0
OPS [(g_capcalc) ] @line 0, column 1 on channel 0
INSTALL [>>] @line 0, column 13 on channel 0
CONVERT [EtnRef] @line 0, column 16 on channel 0
COLON [:] @line 0, column 22 on channel 0
START_D [@] @line 0, column 24 on channel 0
OPS [(appcapcalc.bankcapconfigid)] @line 0, column 25 on channel 0
<<EOS>>
```
It's definitely what I want, except when I checked the finer details, it puts the system into calcmode instead of dmode.   
default -> :exclamation:calcmode -> default -> :heavy_check_mark:convert  -> default ->  :exclamation:calcmode


Then I tried this instead:
XL(g_capcalc) >> EtnRef: CC(appcapcalc.bankcapconfigid)

```
XL(g_capcalc) >> EtnRef: CC(appcapcalc.bankcapconfigid)
START_X [XL] @line 0, column 0 on channel 0
OPS [(g_capcalc) ] @line 0, column 2 on channel 0
INSTALL [>>] @line 0, column 14 on channel 0
CONVERT [EtnRef] @line 0, column 17 on channel 0
COLON [:] @line 0, column 23 on channel 0
START_C [CC] @line 0, column 25 on channel 0
OPS [(appcapcalc.bankcapconfigid)] @line 0, column 27 on channel 0
<<EOS>>
```

default -> :heavy_check_mark:xlmode -> default -> :heavy_check_mark:convert -> default -> :heavy_check_mark:calcmode

This one works too:
$g_capcalc >> EtnRef: XL(appcapcalc.bankcapconfigid)

default -> :heavy_check_mark:lvar -> default -> :heavy_check_mark:convert-> default -> :heavy_check_mark:xlmode


It looks like it's working for most of the modes except one.  Is '@' an unusable sugar character?

**Comment by b3b00** [comment]
'@' is ok as a sugar token.  I ll look at it more thoroughly.

**Comment by b3b00** [comment]
Hello @TamaBaka , fixed with v 3.3.5

**Comment by TamaBaka** [comment]
I can confirm!  Thank you again!  Do you have a tip jar that I can contribute to for your troubles this weekend?

**Comment by b3b00** [comment]
@TamaBaka , no I have no tip jar 🙂. Thanks for wanting to contribute 👍

**Comment by b3b00** [comment]
@TamaBaka , If you're still interested in supporting I've setup a buy me a coffee : https://buymeacoffee.com/b3b00
