### ISSUE TITLE
Slow performance parsing malformed source with "unexpected end of stream errors" using a grammar with many operators

### ISSUE THREAD

**Issue by charliebone** [b3b00/csly#493]
### The Issue
I have defined a grammar and it's working great for my purposes in parsing single line expressions that can consist of mathematical operations, logical comparisons, and some built in function calls. However, I have noticed that when parsing fails due to unexpected end of stream, such as a missing closing parenthesis, there is some serious recursion with many syntactical errors accumulating before the parsing finally fails. 

This seems to really hit an inflection point around the number of operators I have defined. If I run the csly-cli test command with a malformed expression that results in an unexpected end of string, the parsing will take many seconds before it finally comes back. Commenting out even 2 or 3 of the operators and retrying results in a much speedier (though still rather slow) return. Note this performance issue occurs both using the command line utility as well as actual code at parse time. I have presented a grammar file suitable for the cli tool here for ease of reproduction.

Perhaps I have just defined my grammar inefficiently, or there's some clever optimization to be done in this case. Any feedback on resolving this would be appreciated. I'm happy to provide more examples of both working and malformed expressions if you need as well.

To reproduce, use the parser defined below with the csly-cli test command below. Then comment out a few of the defined operators and try again. 

### Malformed source:
```
FUNCTIONCALL([Identifier]
```

### Grammar definition:
```
# lexer spec
genericLexer SlowOnBadParseEosToken;

[AlphaNumId] IDENTIFIER;
[Int] INT;
[Double] NUMBER;
[String] STRING;

[KeyWord] NOT : "NOT";
[KeyWord] AND : "AND";
[KeyWord] OR : "OR";
[KeyWord] XOR : "XOR";
[KeyWord] IS : "IS";
[KeyWord] NULL : "NULL";
[KeyWord] IN : "IN";
[KeyWord] LIKE : "LIKE";
[KeyWord] TRUE : "TRUE";
[KeyWord] FALSE : "FALSE";

[Sugar] EXCLAMATION_POINT : "!";
[Sugar] CARET : "^";
[Sugar] ARITH_PLUS : "+";
[Sugar] ARITH_MINUS : "-";
[Sugar] ARITH_TIMES : "*";
[Sugar] ARITH_DIVIDE : "/";
[Sugar] ARITH_MODULO : "%";

[Sugar] COMP_EQUALS : "=" ;
[Sugar] COMP_NOTEQUALS : "<>" ;
[Sugar] COMP_LT : "<" ;
[Sugar] COMP_GT : ">" ;
[Sugar] COMP_LTE : "<=" ;
[Sugar] COMP_GTE : ">=" ;

[Sugar] COMMA : ",";
[Sugar] PARENS_LEFT : "(";
[Sugar] PARENS_RIGHT : ")";
[Sugar] BRACKET_LEFT : "[";
[Sugar] BRACKET_RIGHT : "]";

# parser spec
parser SlowOnBadParseEos;

-> root: SlowOnBadParseEos_expressions; 

[Prefix 92] NOT ;
[Prefix 91] EXCLAMATION_POINT ;
[Right 71] IN ;
[Right 70] LIKE ;
[Left 40] ARITH_TIMES ;
[Left 40] ARITH_DIVIDE ;
[Left 38] ARITH_MODULO ;
[Left 30] ARITH_PLUS ;
[Left 30] ARITH_MINUS ;
[Prefix 29] ARITH_MINUS ;
[Left 25] COMP_EQUALS ;
[Left 24] COMP_NOTEQUALS ;
[Left 23] COMP_LT ;
[Left 22] COMP_GT ;
[Left 21] COMP_LTE ;
[Left 20] COMP_GTE ;
[Left 15] IS ;
[Left 12] AND ;
[Left 11] OR ;
[Left 10] XOR ;

[Operand] primary : BRACKET_LEFT [d] IDENTIFIER BRACKET_RIGHT [d] ;
[Operand] primary : PARENS_LEFT [d] SlowOnBadParseEos_expressions PARENS_RIGHT [d] ;
[Operand] literal : INT ;
[Operand] literal : NUMBER ;
[Operand] literal : STRING ;
[Operand] literal : [ TRUE | FALSE ] ;
literal : NULL [d] ;
[Operand] literal_list : PARENS_LEFT [d] literal (COMMA [d] literal)* PARENS_RIGHT [d] ; 
[Operand] function_call : IDENTIFIER PARENS_LEFT [d] operand_list PARENS_RIGHT [d] ;
operand_list : SlowOnBadParseEos_expressions (COMMA [d] SlowOnBadParseEos_expressions)* ;

```

**Comment by b3b00** [comment]
Hello @charliebone , indeed expression parsing may cause heavy backtracking and an unexpected end of stream will cause parser to try all and evry possible way so causing slowliness. 
Regarding CLI vs direct CSLY use there is no difference as CLI dynamically generates code to use CSLY. 
I am actually on the process to find all kind of optimization. So your grammar will help me find potential issues.

I will look at it and see if there is some way to optimize it.

Thanks for reporting and using CSLY-CLI. Hope that this tool helped you with using CSLY.

**Comment by b3b00** [comment]
hello @charliebone,

I've found a way to get the parse time real down (from 58s to 233ms !) just reviewing the precedence levels.
Indeed the more different precedence, the more backtracking. So merging some operators in the same precedence level reduces dramatically the parse time. Of course this may not match your need. Here is the grammar i 've used : 

```

genericLexer SlowOnBadParseEosToken;

[AlphaNumId] IDENTIFIER;

[Int] INT;

[Double] NUMBER;

[String] STRING : "\"" "\\";

[KeyWord] NOT : "NOT";

[KeyWord] AND : "AND";

[KeyWord] OR : "OR";

[KeyWord] XOR : "XOR";

[KeyWord] IS : "IS";

[KeyWord] NULL : "NULL";

[KeyWord] IN : "IN";

[KeyWord] LIKE : "LIKE";

[KeyWord] TRUE : "TRUE";

[KeyWord] FALSE : "FALSE";

[Sugar] EXCLAMATION_POINT : "!";

[Sugar] CARET : "^";

[Sugar] ARITH_PLUS : "+";

[Sugar] ARITH_MINUS : "-";

[Sugar] ARITH_TIMES : "*";

[Sugar] ARITH_DIVIDE : "/";

[Sugar] ARITH_MODULO : "%";

[Sugar] COMP_EQUALS : "=";

[Sugar] COMP_NOTEQUALS : "<>";

[Sugar] COMP_LT : "<";

[Sugar] COMP_GT : ">";

[Sugar] COMP_LTE : "<=";

[Sugar] COMP_GTE : ">=";

[Sugar] COMMA : ",";

[Sugar] PARENS_LEFT : "(";

[Sugar] PARENS_RIGHT : ")";

[Sugar] BRACKET_LEFT : "[";

[Sugar] BRACKET_RIGHT : "]";



parser SlowOnBadParseEos;

-> root : SlowOnBadParseEos_expressions;

[Prefix 92] NOT;

[Prefix 91] EXCLAMATION_POINT;

[Prefix 29] ARITH_MINUS;

[Right 71] IN;

[Right 70] LIKE;

[Left 40] ARITH_TIMES;

[Left 40] ARITH_DIVIDE;

[Left 40] ARITH_MODULO;

[Left 30] ARITH_PLUS;

[Left 30] ARITH_MINUS;

[Left 25] COMP_EQUALS;

[Left 25] COMP_NOTEQUALS;

[Left 25] COMP_LT;

[Left 25] COMP_GT;

[Left 25] COMP_LTE;

[Left 25] COMP_GTE;

[Left 15] IS;

[Left 12] AND;

[Left 11] OR;

[Left 11] XOR;

[Operand] primary : BRACKET_LEFT IDENTIFIER BRACKET_RIGHT;

[Operand] primary : PARENS_LEFT SlowOnBadParseEos_expressions PARENS_RIGHT;

[Operand] literal : INT;

[Operand] literal : NUMBER;

[Operand] literal : STRING;

[Operand] literal : [ TRUE | FALSE ];

[Operand] literal_list : PARENS_LEFT literal (COMMA literal) * PARENS_RIGHT;

[Operand] function_call : IDENTIFIER PARENS_LEFT operand_list PARENS_RIGHT;

[Operand] literal : NULL;

operand_list : SlowOnBadParseEos_expressions (COMMA SlowOnBadParseEos_expressions) *;

```

**Comment by charliebone** [comment]
Hi Olivier,

Thanks for responding so promptly! csly is indeed an excellent library and I've found it tremendously useful for my purpose. Basically I went from wondering if something was possible to actually making it happen in a very short time because of csly. 

That's interesting and indeed makes sense that consolidating the precedence of the operators reduces the number of paths in the tree that need to be backtracked in the case of an EOS. I can certainly combine a good amount of the precedence there, especially given the fact that csly is able to provide left associativity for an LL grammar. 

Feel free to close this issue if you'd like, I left it open in case you were doing any other performance digging for this case but honestly the solution you offered of combining precedence works for me. Thanks again!

**Comment by b3b00** [comment]
Thanks for your feedback @charliebone . I jeep the issue opened as I have identified an issue with error management that causes slow down. Specifically when source does not match the grammar and when the grammar implies deep backtracking.

Thanks for reporting this issue

**Comment by b3b00** [comment]
Once again thanks for your issue @charliebone , I've found a useless a really costy thing in CSLY. Removing it your base parser (whitout any modification) goes from 58 sec. to 14 sec !  sadly 2 unit tests turn red, I have to look at it and keep on profiling this grammar to hoply find even better optimizations.

**Comment by b3b00** [comment]
@charliebone , it's now ok. And happily it also address #414 !
i will merge and publish an new version quickly
Thanks for your help

**Comment by b3b00** [comment]
Version 3.4.0 is published. Feel free to comment.

**Comment by charliebone** [comment]
Brilliant, with the new nuget and revised grammar with consolidated precedence, everything is working great.

One very minor suggestion is that given you are checking for containment at insertion time of errors in the SyntaxParseResult class, the use of a HashSet instead of a list to store the parse errors may be beneficial if the list size could potentially be larger than a few errors.

Thanks again for your help with all this!
