### ISSUE TITLE
CS0655 on Attrbiute contains Property `Channel`

### ISSUE THREAD

**Issue by bdke** [b3b00/csly#499]
### Info
- Version: 3.4.4
- .net Version: 8.0.100
- OS: Windows 10

### Summary
`Channel` is `int?` and `Nullable` in Attribute would cause CS0655

### Reproduce
```c#
[Upto("\"", Channel = 1)] //this will cause CS0655
Test
```

Maybe i will fix this by myself
would make a pr after fixed

**Comment by b3b00** [comment]
Hello @bdke , I would greatly appreciate a PR for this . thanks for your help

**Comment by b3b00** [comment]
@bdke , think to join some additional unit tests to check for instance that upto token goes to the correct channel

**Comment by bdke** [comment]
Upto Token is not in the correct channel
i have already specified the Channel to 1
