### ISSUE TITLE
how to use value option

### ISSUE THREAD

**Issue by MrMuMu** [b3b00/csly#94]
[Production("ComparisonExpr: StringConcatExpr (GeneralComp StringConcatExpr)?")]
    public string ComparisonExpr(string stringConcatExpr, ValueOption<Group<string, string>> option)

    [Production("StringConcatExpr: STRING")]
    public string StringConcatExpr(Token<TokenEnum> value)

    [Production("GeneralComp: GENERALCOMPARATOR")]
    public string GeneralComp(Token<TokenEnum> token)

I have the grammar, above. In `ComparisonExpr:` I have a group clause which consists of non-terminals. What should I use in the parameters of the function `ComparisonExpr` to have the value of the group in the `option` parameter.

Also, is (TERMINAL NON_TERMINAL) clauses supported?
For example: StringConcatExpr (COMMA StringConcatExpr)?
What should be the function signature for this?

**Comment by b3b00** [comment]
[Production("ComparisonExpr: StringConcatExpr (GeneralComp StringConcatExpr)?")]
    public string ComparisonExpr(string stringConcatExpr, ValueOption<Group<string, string>> option)

    [Production("StringConcatExpr: STRING")]
    public string StringConcatExpr(Token<TokenEnum> value)

    [Production("GeneralComp: GENERALCOMPARATOR")]
    public string GeneralComp(Token<TokenEnum> token)

I have the grammar, above. In `ComparisonExpr:` I have a group clause which consists of non-terminals. What should I use in the parameters of the function `ComparisonExpr` to have the value of the group in the `option` parameter.

yourComparisonExpr method signature is wrong' must be 

```
public string ComparisonExpr(string stringConcatExpr, ValueOption<Group<TokenEnum,string>> option)
```
The type of ghe option param is option.IsSome and then get the value (a Group<Tokennum,string>, let's call it group)with option.Value.
then using the group, you can get the value f the first nonterm using group.Value(0)



Also, is (TERMINAL NON_TERMINAL) clauses supported?

yes indeed it is.In your example, you get the terminal TERMINAL value using group.Token(0) and non term NON_TERMINAL value with group.Value(1)


For example: StringConcatExpr (COMMA StringConcatExpr)?
What should be the function signature for this?

very similar to ComparisonExpr


```
StringoncatExpr(ValueOption<Group<TokenEnum,string>> option)
```

**Comment by b3b00** [comment]
more on options ang groups can be found in the wiki https://github.com/b3b00/csly/wiki/EBNF-parser

**Comment by MrMuMu** [comment]
> public string ComparisonExpr(string stringConcatExpr, ValueOption<Group<TokenEnum, string>> option)

I have tested what you had suggested, however I get the following output:

> OUTCH Object of type 'sly.parser.parser.ValueOption`1[System.String]' cannot be converted to type 'sly.parser.parser.ValueOption`1[sly.parser.parser.Group`2[netSchematron.TokenEnum,System.String]]'. calling ComparisonExpr__StringConcatExpr_GROUP-GeneralComp-StringConcatExpr? =>  ComparisonExpr

**Comment by b3b00** [comment]
Couleur you direct me to tour test repo , i will look at it.

**Comment by MrMuMu** [comment]
https://github.com/MrMuMu/netSchematron very appreciated for spending time:)

**Comment by MrMuMu** [comment]
looking forward to your feedback

**Comment by b3b00** [comment]
Hi @MrMuMu , 
2 things seem to involved here : 

- a bad lexer configuration
- an bug in error reporting, that turns the lexing problem in a violent stacktrace.

Back to work in real life now, so I will follow investigation later

**Comment by b3b00** [comment]
yes indeed it is. You can't have the same int value for an enum value.  It's illegal C#.
So making NODECOMPARATOR = 14589 (a dummy example here), or any unused int value in your enum should solve your problem.
Nevertheless there is a real  bug in optional group parsing error reporting. I think I 've found and corrected it and will check later to commit it on dev branch.

**Comment by b3b00** [comment]
I have just pushed a little bugfix for error reporting : https://github.com/b3b00/csly/commit/707727ecd60511f042c49f80f2165ca3d5c5aac6

I can confirm that your lexer problem is the one you found. So just fix your enum values and it'll all work fine.
