### ISSUE TITLE
Possible leading tokens

### ISSUE THREAD

**Issue by MrMuMu** [b3b00/csly#95]
// other rules leads to UnaryExpr from root
    [Production("UnaryExpr: PLUS* ValueExpr")]
    // other rules leading to IntegerLiteral from ValueExpr
    [Production("IntegerLiteral: INTEGER")]

In such a grammar, since `PLUS` can occur zero times or more, in case of `PLUS` occurs zero times, possible leading tokens of `ValueExpr` should be added to rules prior to `ValueExpr`. Am I right? Because right now I am unable parse "2 + 2" because possible leading tokens does not contain INTEGER token.

**Comment by b3b00** [comment]
I am not sure what you are trying to do. I looked at your netschematron repo and I guess yiu shiuld have a look at https://github.com/b3b00/csly/wiki/expression-parsing . CSLY offers a way to express expression parsers in a very compact and declarative way. Sure it would help you in building the expressions part of xpath.

But yeah you're right INTEGER should be a possible leading token. maybe you've found a left recursion problem. Once again take a  closer look at the exoressions parsing feature.

**Comment by b3b00** [comment]
Please send a full example, and I will look at it.

**Comment by MrMuMu** [comment]
Your expression-parsing example gave me some ideas after I try that I will get back to you. Thank you for your help again:)

**Comment by b3b00** [comment]
Can I close this issue ?

**Comment by MrMuMu** [comment]
Your choice. If you leave it open, if I need to ask something related to this topic, I will post here, if you close I can open a new issue.
